// extension/src/apps/menu/tools/AutoClick.vue
<template>
    <div v-if="isRecording && recordingPointerPosition" class="recording-pointer-overlay" aria-hidden="true">
        <div v-for="segment in crosshairSegments" :key="segment.key" class="recording-crosshair-line"
            :class="segment.className" :style="segment.style"></div>
        <div v-if="hoveredButtonRect" class="recording-button-outline" :style="buttonOutlineStyle"></div>
        <div class="recording-coordinate-badge" :style="coordinateBadgeStyle">
            <span>clientX {{ recordingPointerPosition.x }}</span>
            <span>clientY {{ recordingPointerPosition.y }}</span>
        </div>
    </div>
    <Draggable :canOverflow="false">
        <div v-show="visible" class="auto-clicker-card">
            <h1>
                <span>🖱️ 连点器 · 统一间隔</span>
            </h1>
            <div class="subhead">
                录制点击序列 · 统一间隔控制 · 快捷键 <kbd>Ctrl+Shift+L</kbd> 切换播放
            </div>

            <div class="control-group">
                <label for="intervalInput">
                    ⏱️ 间隔 (ms)
                </label>
                <input id="intervalInput" v-model.number="intervalMs" type="number" :min="50" :max="10000" step="50"
                    @change="onIntervalChange">
                <span class="unit-label">ms</span>
            </div>

            <div class="btn-group">
                <button class="btn btn-primary" :disabled="isPlaying || isRecording" @click="startPlayback">
                    ▶ 播放
                </button>
                <button class="btn btn-danger" :disabled="!isPlaying" @click="stopPlayback">
                    ⏹ 停止
                </button>
                <button class="btn btn-success" :class="{ 'btn-recording': isRecording }" @click="toggleRecording">
                    {{ isRecording ? '⏹ 停止录制' : '🔴 录制' }}
                </button>
                <button class="btn btn-outline" @click="resetCounter">
                    ⟳ 重置计数
                </button>
            </div>

            <div class="delay-hint">
                <span>💡</span>
                <span>所有步骤使用统一的间隔时间，适合弹窗延迟较固定的场景</span>
            </div>

            <div class="status-box">
                <div class="status-indicator">
                    <span class="status-dot" :class="statusDotClass"></span>
                    <span style="font-weight: 450; color: #1e2a44;">{{ statusText }}</span>
                    <span class="record-steps">步骤: {{ recordedSteps.length }}</span>
                </div>
                <div class="click-counter">
                    <span>点击</span>
                    <span>{{ clickCounter }}</span>
                </div>
            </div>
            <div class="footer-note">
                <span>⚡ 录制时点击页面任意位置记录坐标</span>
                <span>· 再次点击录制按钮结束</span>
            </div>
        </div>
    </Draggable>
</template>

<script setup lang="ts">
import { ref, computed, onBeforeUnmount, onMounted } from 'vue';
import { Draggable } from '@components/index';  // 拖拽库

const props = defineProps<{
    visible: boolean;
}>();
// ---------- 响应式状态 ----------
const intervalMs = ref(500);           // 间隔时间（毫秒）
const clickCounter = ref(0);          // 累计点击次数
const isPlaying = ref(false);         // 是否正在播放
const isRecording = ref(false);       // 是否正在录制
const recordedSteps = ref<{ x: number; y: number }[]>([]);        // 录制步骤 [{ x, y }]
const currentStepIndex = ref(0);      // 回放当前步骤索引

// ---------- 内部状态 ----------
const intervalId = ref<NodeJS.Timeout | null>(null);               // 播放定时器
const recordingClickListenerTimer = ref<number | null>(null);
type PointerPosition = {
    x: number;
    y: number;
};

type ViewportRect = {
    left: number;
    top: number;
    right: number;
    bottom: number;
    width: number;
    height: number;
};

const recordingPointerPosition = ref<PointerPosition | null>(null);
const hoveredButtonRect = ref<ViewportRect | null>(null);
const buttonSelector = 'button, [role="button"], input[type="button"], input[type="submit"], input[type="reset"]';

// 监听鼠标点击
const recordingListener = function (e: MouseEvent) {
  if (!isRecording.value) {return;}
  const x = e.clientX;
  const y = e.clientY;
  recordedSteps.value.push({ x, y });
};

// ---------- 计算属性 ----------
const statusText = computed(() => {
  if (isRecording.value) {return '录制中';}
  if (isPlaying.value) {return '播放中';}
  return '空闲';
});

const statusDotClass = computed(() => {
  if (isRecording.value) {return 'recording';}
  if (isPlaying.value) {return 'active';}
  return 'inactive';
});

const crosshairSegments = computed(() => {
  const pointer = recordingPointerPosition.value;
  if (!pointer) {return [];}

  const buttonRect = hoveredButtonRect.value;
  const x = `${pointer.x}px`;
  const y = `${pointer.y}px`;

  if (!buttonRect) {
    return [
      {
        key: 'vertical',
        className: 'recording-crosshair-line--vertical',
        style: {
          left: x,
          top: '0px',
          height: '100vh'
        }
      },
      {
        key: 'horizontal',
        className: 'recording-crosshair-line--horizontal',
        style: {
          left: '0px',
          top: y,
          width: '100vw'
        }
      }
    ];
  }

  return [
    {
      key: 'vertical-top',
      className: 'recording-crosshair-line--vertical',
      style: {
        left: x,
        top: '0px',
        height: `${Math.max(0, buttonRect.top)}px`
      }
    },
    {
      key: 'vertical-bottom',
      className: 'recording-crosshair-line--vertical',
      style: {
        left: x,
        top: `${buttonRect.bottom}px`,
        height: `calc(100vh - ${buttonRect.bottom}px)`
      }
    },
    {
      key: 'horizontal-left',
      className: 'recording-crosshair-line--horizontal',
      style: {
        left: '0px',
        top: y,
        width: `${Math.max(0, buttonRect.left)}px`
      }
    },
    {
      key: 'horizontal-right',
      className: 'recording-crosshair-line--horizontal',
      style: {
        left: `${buttonRect.right}px`,
        top: y,
        width: `calc(100vw - ${buttonRect.right}px)`
      }
    }
  ];
});

const coordinateBadgeStyle = computed(() => {
  const pointer = recordingPointerPosition.value;
  if (!pointer) {return {};}

  return {
    left: `max(8px, min(calc(100vw - 132px), ${pointer.x + 12}px))`,
    top: `max(8px, min(calc(100vh - 42px), ${pointer.y + 12}px))`
  };
});

const buttonOutlineStyle = computed(() => {
  const buttonRect = hoveredButtonRect.value;
  if (!buttonRect) {return {};}

  return {
    left: `${buttonRect.left}px`,
    top: `${buttonRect.top}px`,
    width: `${buttonRect.width}px`,
    height: `${buttonRect.height}px`
  };
});

// ---------- 核心功能 ----------
// 执行一次点击 (指定坐标)
function performClickAt(x: number, y: number) {
  const eventOptions = {
    view: window,
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: window.screenX + x || x,
    screenY: window.screenY + y || y,
    buttons: 1,
    button: 0
  };

  // mousedown
  const downEvent = new MouseEvent('mousedown', eventOptions);
  document.dispatchEvent(downEvent);

  // mouseup (buttons: 0)
  const upOptions = { ...eventOptions, buttons: 0 };
  const upEvent = new MouseEvent('mouseup', upOptions);
  document.dispatchEvent(upEvent);

  // click
  const clickEvent = new MouseEvent('click', {
    view: window,
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: window.screenX + x || x,
    screenY: window.screenY + y || y,
    button: 0,
    buttons: 0
  });
  document.dispatchEvent(clickEvent);

  clickCounter.value++;
}

// 播放下一个步骤
function playNextStep() {
  if (!isPlaying.value) {return;}
  if (recordedSteps.value.length === 0) {
    stopPlayback();
    return;
  }

  // 执行当前步骤
  const step = recordedSteps.value[currentStepIndex.value];
  performClickAt(step.x, step.y);

  // 移动到下一步（循环）
  currentStepIndex.value++;
  if (currentStepIndex.value >= recordedSteps.value.length) {
    currentStepIndex.value = 0;
  }
}

// 开始播放
function startPlayback() {
  if (isPlaying.value) {return;}
  if (isRecording.value) {
    stopRecording();
  }
  if (recordedSteps.value.length === 0) {
    // 可以添加提示
    return;
  }

  // 重置步骤索引
  currentStepIndex.value = 0;
  isPlaying.value = true;

  // 清除旧定时器
  if (intervalId.value) {
    clearInterval(intervalId.value);
    intervalId.value = null;
  }

  // 创建新定时器
  intervalId.value = setInterval(playNextStep, intervalMs.value);

  // 立即执行第一步
  playNextStep();
}

// 停止播放
function stopPlayback() {
  if (intervalId.value) {
    clearInterval(intervalId.value);
    intervalId.value = null;
  }
  isPlaying.value = false;
}

// ---------- 录制功能 ----------
function getViewportRect(rect: DOMRect): ViewportRect {
  const left = Math.max(0, rect.left);
  const top = Math.max(0, rect.top);
  const right = Math.min(window.innerWidth, rect.right);
  const bottom = Math.min(window.innerHeight, rect.bottom);

  return {
    left,
    top,
    right,
    bottom,
    width: Math.max(0, right - left),
    height: Math.max(0, bottom - top)
  };
}

function getButtonRectAtPoint(x: number, y: number) {
  const pointedElement = document.elementFromPoint(x, y);
  const buttonElement = pointedElement instanceof Element
    ? pointedElement.closest(buttonSelector)
    : null;

  if (!(buttonElement instanceof HTMLElement)) {
    return null;
  }

  const rect = buttonElement.getBoundingClientRect();
  if (rect.width <= 0 || rect.height <= 0) {
    return null;
  }

  return getViewportRect(rect);
}

function updateRecordingPointer(x: number, y: number) {
  const pointer = {
    x: Math.round(x),
    y: Math.round(y)
  };

  recordingPointerPosition.value = pointer;
  hoveredButtonRect.value = getButtonRectAtPoint(pointer.x, pointer.y);
}

function handleRecordingPointerMove(e: MouseEvent) {
  if (!isRecording.value) {return;}
  updateRecordingPointer(e.clientX, e.clientY);
}

function refreshRecordingPointerTarget() {
  if (!isRecording.value || !recordingPointerPosition.value) {return;}
  const { x, y } = recordingPointerPosition.value;
  hoveredButtonRect.value = getButtonRectAtPoint(x, y);
}

function addRecordingPointerListeners() {
  document.addEventListener('mousemove', handleRecordingPointerMove, { passive: true });
  document.addEventListener('scroll', refreshRecordingPointerTarget, true);
  window.addEventListener('resize', refreshRecordingPointerTarget);
}

function removeRecordingPointerListeners() {
  document.removeEventListener('mousemove', handleRecordingPointerMove);
  document.removeEventListener('scroll', refreshRecordingPointerTarget, true);
  window.removeEventListener('resize', refreshRecordingPointerTarget);
}

function addRecordingClickListener(defer: boolean) {
  if (recordingClickListenerTimer.value !== null) {
    window.clearTimeout(recordingClickListenerTimer.value);
    recordingClickListenerTimer.value = null;
  }

  if (!defer) {
    document.addEventListener('click', recordingListener);
    return;
  }

  recordingClickListenerTimer.value = window.setTimeout(() => {
    recordingClickListenerTimer.value = null;
    if (isRecording.value) {
      document.addEventListener('click', recordingListener);
    }
  }, 0);
}

function removeRecordingClickListener() {
  if (recordingClickListenerTimer.value !== null) {
    window.clearTimeout(recordingClickListenerTimer.value);
    recordingClickListenerTimer.value = null;
  }
  document.removeEventListener('click', recordingListener);
}

function startRecording(e?: MouseEvent) {
  if (isRecording.value) {return;}
  if (isPlaying.value) {
    stopPlayback();
  }

  // 清空之前的录制
  recordedSteps.value = [];
  currentStepIndex.value = 0;
  isRecording.value = true;

  if (e) {
    updateRecordingPointer(e.clientX, e.clientY);
  }

  addRecordingClickListener(Boolean(e));
  addRecordingPointerListeners();
}

function stopRecording() {
  if (!isRecording.value) {return;}
  isRecording.value = false;
  removeRecordingClickListener();
  removeRecordingPointerListeners();
  recordingPointerPosition.value = null;
  hoveredButtonRect.value = null;
  console.warn(recordedSteps.value);
}

function toggleRecording(e?: MouseEvent) {
  if (isRecording.value) {
    stopRecording();
  } else {
    startRecording(e);
  }
}

// ---------- 其他功能 ----------
function resetCounter() {
  clickCounter.value = 0;
}

function onIntervalChange() {
  // 确保值在有效范围内
  if (intervalMs.value < 50) {intervalMs.value = 50;}
  if (intervalMs.value > 10000) {intervalMs.value = 10000;}

  // 如果正在播放，重启以应用新间隔
  if (isPlaying.value) {
    stopPlayback();
    startPlayback();
  }
}

// ---------- 键盘快捷键 ----------
function handleKeydown(e: KeyboardEvent) {
  const isCtrl = e.ctrlKey || e.metaKey;
  const isShift = e.shiftKey;

  // Ctrl+Shift+L: 播放/停止
  if (isCtrl && isShift && (e.key === 'l' || e.key === 'L')) {
    e.preventDefault();
    if (isRecording.value) {
      stopRecording();
    }
    if (isPlaying.value) {
      stopPlayback();
    } else {
      startPlayback();
    }
  }

  // Ctrl+Shift+R: 录制/停止录制
  if (isCtrl && isShift && (e.key === 'r' || e.key === 'R')) {
    e.preventDefault();
    toggleRecording();
  }
}

// ---------- 生命周期 ----------
onBeforeUnmount(() => {
  // 清理定时器和事件监听
  if (intervalId.value) {
    clearInterval(intervalId.value);
    intervalId.value = null;
  }
  removeRecordingClickListener();
  removeRecordingPointerListeners();
  document.removeEventListener('keydown', handleKeydown);
});

onMounted(() => {
  document.addEventListener('keydown', handleKeydown);
});
</script>

<style scoped lang="scss">
.recording-pointer-overlay {
    position: fixed;
    inset: 0;
    z-index: 2147483647;
    pointer-events: none;
    color: #ef4444;
}

.recording-crosshair-line {
    position: fixed;
    background: rgba(239, 68, 68, 0.78);
    box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.38);
}

.recording-crosshair-line--vertical {
    width: 1px;
}

.recording-crosshair-line--horizontal {
    height: 1px;
}

.recording-button-outline {
    position: fixed;
    border: 2px solid #ef4444;
    border-radius: 8px;
    box-shadow: 0 0 0 2px rgba(255, 255, 255, 0.82), 0 0 18px rgba(239, 68, 68, 0.28);
}

.recording-coordinate-badge {
    position: fixed;
    display: inline-flex;
    flex-direction: column;
    gap: 2px;
    min-width: 120px;
    padding: 5px 8px;
    border: 1px solid rgba(239, 68, 68, 0.45);
    border-radius: 8px;
    background: rgba(15, 23, 42, 0.88);
    box-shadow: 0 8px 20px rgba(15, 23, 42, 0.22);
    color: #f8fafc;
    font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace;
    font-size: 10px;
    line-height: 1.2;
    letter-spacing: 0;
    white-space: nowrap;
}

.auto-clicker-card {
    background: rgba(255, 255, 255, 0.7);
    backdrop-filter: blur(6px);
    -webkit-backdrop-filter: blur(6px);
    border-radius: 24px;
    box-shadow: 0 10px 20px rgba(0, 10, 30, 0.15), 0 3px 6px rgba(0, 0, 0, 0.05);
    padding: 18px 20px 21px;
    max-width: 280px;
    width: 100%;
    transition: all 0.2s ease;
    border: 1px solid rgba(255, 255, 255, 0.5);
}

h1 {
    font-size: 14px;
    font-weight: 600;
    margin: 0 0 4px 0;
    color: #0b1a33;
    letter-spacing: 0;
    display: flex;
    align-items: center;
    gap: 4px;
}

.subhead {
    color: #3a4a62;
    font-size: 11px;
    font-weight: 400;
    margin: 0 0 14px 0;
    border-left: 2px solid #3b82f6;
    padding-left: 7px;
    background: rgba(59, 130, 246, 0.06);
    border-radius: 0 6px 6px 0;
    line-height: 1.35;
}

.control-group {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 6px 8px;
    background: rgba(255, 255, 255, 0.5);
    padding: 9px 10px;
    border-radius: 30px;
    margin-bottom: 10px;
    backdrop-filter: blur(2px);
    border: 1px solid rgba(255, 255, 255, 0.8);
}

.control-group label {
    font-weight: 500;
    color: #1e2a44;
    font-size: 11px;
    letter-spacing: 0;
    display: flex;
    align-items: center;
    gap: 3px;
}

.control-group input[type="number"] {
    width: 56px;
    padding: 5px 7px;
    border: 1px solid #cdd9e9;
    border-radius: 20px;
    font-size: 12px;
    font-weight: 500;
    background: white;
    box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.02);
    transition: 0.2s;
    color: #0b1a33;
}

.control-group input[type="number"]:focus {
    outline: none;
    border-color: #3b82f6;
    box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.2);
}

.control-group input[type="number"]::-webkit-inner-spin-button {
    opacity: 0.6;
}

.unit-label {
    margin-left: -2px;
    color: #4a5a72;
    font-size: 11px;
}

.btn-group {
    display: flex;
    gap: 5px;
    flex-wrap: wrap;
    margin: 3px 0 8px;
}

.btn {
    flex: 1 1 auto;
    min-width: 40px;
    padding: 7px 9px;
    border: none;
    border-radius: 30px;
    font-weight: 600;
    font-size: 11px;
    background: white;
    color: #1e2a44;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.02), 0 1px 2px rgba(0, 0, 0, 0.02);
    cursor: pointer;
    transition: 0.15s ease;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 3px;
    border: 1px solid #dbe1ed;
    letter-spacing: 0;
}

.btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
}

.btn-primary {
    background: #1a2a4a;
    color: white;
    border: 1px solid #1a2a4a;
    box-shadow: 0 4px 8px -3px rgba(26, 42, 74, 0.2);
}

.btn-primary:hover:not(:disabled) {
    background: #0f1e38;
    transform: scale(0.97);
}

.btn-danger {
    background: #b91c1c;
    color: white;
    border: 1px solid #b91c1c;
    box-shadow: 0 4px 8px -3px rgba(185, 28, 28, 0.2);
}

.btn-danger:hover:not(:disabled) {
    background: #991b1b;
    transform: scale(0.97);
}

.btn-success {
    background: #0b6e4f;
    color: white;
    border: 1px solid #0b6e4f;
    box-shadow: 0 4px 8px -3px rgba(11, 110, 79, 0.2);
}

.btn-success:hover:not(:disabled) {
    background: #095a40;
    transform: scale(0.97);
}

.btn-outline {
    background: transparent;
    border: 1px solid #b0c2db;
}

.btn-outline:hover:not(:disabled) {
    background: rgba(255, 255, 255, 0.5);
}

.btn-recording {
    background: #dc2626;
    color: white;
    border: 1px solid #dc2626;
    animation: pulse-rec 1s infinite;
    box-shadow: 0 0 0 1px rgba(220, 38, 38, 0.3);
}

@keyframes pulse-rec {
    0% {
        box-shadow: 0 0 0 0 rgba(220, 38, 38, 0.5);
    }

    70% {
        box-shadow: 0 0 0 4px rgba(220, 38, 38, 0);
    }

    100% {
        box-shadow: 0 0 0 0 rgba(220, 38, 38, 0);
    }
}

.delay-hint {
    background: #fef3c7;
    padding: 5px 8px;
    border-radius: 15px;
    font-size: 10px;
    color: #92400e;
    margin-top: 6px;
    border: 1px solid #fde68a;
    display: flex;
    align-items: center;
    gap: 4px;
    line-height: 1.35;
}

.status-box {
    background: #eef2f8;
    padding: 9px 11px;
    border-radius: 15px;
    margin-top: 9px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 6px 10px;
    border: 1px solid rgba(255, 255, 255, 0.7);
}

.status-indicator {
    display: flex;
    align-items: center;
    gap: 6px;
    font-weight: 450;
    font-size: 11px;
}

.status-dot {
    display: inline-block;
    width: 7px;
    height: 7px;
    border-radius: 10px;
    background: #7a8aa3;
    transition: 0.2s;
    box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.05);
}

.status-dot.active {
    background: #22a65e;
    box-shadow: 0 0 0 2px rgba(34, 166, 94, 0.2);
}

.status-dot.recording {
    background: #dc2626;
    box-shadow: 0 0 0 2px rgba(220, 38, 38, 0.3);
    animation: pulse-dot 1s infinite;
}

@keyframes pulse-dot {
    0% {
        opacity: 1;
        transform: scale(1);
    }

    50% {
        opacity: 0.6;
        transform: scale(0.9);
    }

    100% {
        opacity: 1;
        transform: scale(1);
    }
}

.status-dot.inactive {
    background: #b0bcca;
}

.click-counter {
    background: white;
    padding: 3px 10px 3px 9px;
    border-radius: 30px;
    font-size: 12px;
    font-weight: 600;
    color: #0b1a33;
    box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.02);
    border: 1px solid #dbe1ed;
    display: flex;
    align-items: center;
    gap: 6px;
}

.click-counter span {
    font-weight: 400;
    font-size: 10px;
    color: #3a4a62;
}

.record-steps {
    font-size: 10px;
    background: rgba(0, 0, 0, 0.02);
    padding: 2px 7px;
    border-radius: 20px;
    color: #2c3e5c;
}

.footer-note {
    margin-top: 12px;
    font-size: 10px;
    color: #5a6e8a;
    text-align: center;
    border-top: 1px dashed #ccd8e8;
    padding-top: 10px;
    letter-spacing: 0;
    display: flex;
    justify-content: center;
    gap: 8px;
    flex-wrap: wrap;
}

.footer-note kbd {
    background: #e2e8f2;
    padding: 1px 5px;
    border-radius: 15px;
    font-size: 10px;
    font-weight: 600;
    color: #1a2a4a;
}

@media (max-width: 480px) {
    .auto-clicker-card {
        padding: 12px 9px;
        max-width: 260px;
    }

    .control-group {
        border-radius: 16px;
        padding: 7px 8px;
    }

    .btn-group .btn {
        min-width: 35px;
        padding: 6px;
        font-size: 10px;
    }
}
</style>

// extension/src/apps/menu/tools/AutoClick.tsx
/**
 * AutoClick 自动点击器组件（React 版）
 * 从 AutoClick.vue 迁移而来
 *
 * 关键变更：
 * - Vue ref → useState（渲染相关）/ useRef（定时器、监听器引用）
 * - computed → useMemo
 * - Draggable.vue → React 版 Draggable（@/assets/components/react-index）
 * - 事件监听器用 ref 存储最新版本 + 稳定包装函数，避免 stale closure
 * - setInterval 回调用 ref 存储最新 playNextStep，确保调用最新逻辑
 *
 * 顺序约束：稳定包装函数必须在 add/remove 监听器函数之前声明，
 * 工具函数在业务函数之前，ref.current 赋值在所有函数定义之后。
 */
import React, { useState, useRef, useEffect, useMemo, useCallback } from "react";
import { Draggable } from "@/assets/components/react-index";
import "./styles/auto-click.scss";

interface AutoClickProps {
  visible: boolean;
}

interface PointerPosition {
  x: number;
  y: number;
}

interface ViewportRect {
  left: number;
  top: number;
  right: number;
  bottom: number;
  width: number;
  height: number;
}

interface CrosshairSegment {
  key: string;
  className: string;
  style: React.CSSProperties;
}

const buttonSelector =
  'button, [role="button"], input[type="button"], input[type="submit"], input[type="reset"]';

const AutoClick: React.FC<AutoClickProps> = ({ visible }) => {
  // ---------- 响应式状态 ----------
  const [intervalMs, setIntervalMs] = useState(500);
  const [clickCounter, setClickCounter] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [recordedSteps, setRecordedSteps] = useState<PointerPosition[]>([]);
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [recordingPointerPosition, setRecordingPointerPosition] =
    useState<PointerPosition | null>(null);
  const [hoveredButtonRect, setHoveredButtonRect] = useState<ViewportRect | null>(null);

  // ---------- 内部状态（用 ref，不需要触发重渲染） ----------
  const intervalIdRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const recordingClickListenerTimerRef = useRef<number | null>(null);

  // ---------- ref 存储事件处理函数最新版本 ----------
  const playNextStepRef = useRef<() => void>(() => {});
  const recordingListenerRef = useRef<(e: MouseEvent) => void>(() => {});
  const handleRecordingPointerMoveRef = useRef<(e: MouseEvent) => void>(() => {});
  const refreshRecordingPointerTargetRef = useRef<() => void>(() => {});
  const handleKeydownRef = useRef<(e: KeyboardEvent) => void>(() => {});

  // ---------- 稳定包装函数（引用永远不变，用于 add/removeEventListener） ----------
  const playNextStepStable = useCallback(() => playNextStepRef.current(), []);
  const recordingListenerStable = useCallback(
    (e: MouseEvent) => recordingListenerRef.current(e),
    []
  );
  const handleRecordingPointerMoveStable = useCallback(
    (e: MouseEvent) => handleRecordingPointerMoveRef.current(e),
    []
  );
  const refreshRecordingPointerTargetStable = useCallback(
    () => refreshRecordingPointerTargetRef.current(),
    []
  );
  const handleKeydownStable = useCallback(
    (e: KeyboardEvent) => handleKeydownRef.current(e),
    []
  );

  // ---------- 计算属性 ----------
  const statusText = useMemo(() => {
    if (isRecording) return "录制中";
    if (isPlaying) return "播放中";
    return "空闲";
  }, [isRecording, isPlaying]);

  const statusDotClass = useMemo(() => {
    if (isRecording) return "recording";
    if (isPlaying) return "active";
    return "inactive";
  }, [isRecording, isPlaying]);

  const crosshairSegments = useMemo<CrosshairSegment[]>(() => {
    const pointer = recordingPointerPosition;
    if (!pointer) return [];

    const buttonRect = hoveredButtonRect;
    const x = `${pointer.x}px`;
    const y = `${pointer.y}px`;

    if (!buttonRect) {
      return [
        {
          key: "vertical",
          className: "recording-crosshair-line--vertical",
          style: { left: x, top: "0px", height: "100vh" },
        },
        {
          key: "horizontal",
          className: "recording-crosshair-line--horizontal",
          style: { left: "0px", top: y, width: "100vw" },
        },
      ];
    }

    return [
      {
        key: "vertical-top",
        className: "recording-crosshair-line--vertical",
        style: { left: x, top: "0px", height: `${Math.max(0, buttonRect.top)}px` },
      },
      {
        key: "vertical-bottom",
        className: "recording-crosshair-line--vertical",
        style: {
          left: x,
          top: `${buttonRect.bottom}px`,
          height: `calc(100vh - ${buttonRect.bottom}px)`,
        },
      },
      {
        key: "horizontal-left",
        className: "recording-crosshair-line--horizontal",
        style: { left: "0px", top: y, width: `${Math.max(0, buttonRect.left)}px` },
      },
      {
        key: "horizontal-right",
        className: "recording-crosshair-line--horizontal",
        style: {
          left: `${buttonRect.right}px`,
          top: y,
          width: `calc(100vw - ${buttonRect.right}px)`,
        },
      },
    ];
  }, [recordingPointerPosition, hoveredButtonRect]);

  const coordinateBadgeStyle = useMemo<React.CSSProperties>(() => {
    const pointer = recordingPointerPosition;
    if (!pointer) return {};
    return {
      left: `max(8px, min(calc(100vw - 132px), ${pointer.x + 12}px))`,
      top: `max(8px, min(calc(100vh - 42px), ${pointer.y + 12}px))`,
    };
  }, [recordingPointerPosition]);

  const buttonOutlineStyle = useMemo<React.CSSProperties>(() => {
    const buttonRect = hoveredButtonRect;
    if (!buttonRect) return {};
    return {
      left: `${buttonRect.left}px`,
      top: `${buttonRect.top}px`,
      width: `${buttonRect.width}px`,
      height: `${buttonRect.height}px`,
    };
  }, [hoveredButtonRect]);

  // ---------- 纯工具函数 ----------
  const performClickAt = useCallback((x: number, y: number) => {
    const eventOptions = {
      view: window,
      bubbles: true,
      cancelable: true,
      clientX: x,
      clientY: y,
      screenX: window.screenX + x || x,
      screenY: window.screenY + y || y,
      buttons: 1,
      button: 0,
    };

    document.dispatchEvent(new MouseEvent("mousedown", eventOptions));
    document.dispatchEvent(
      new MouseEvent("mouseup", { ...eventOptions, buttons: 0 })
    );
    document.dispatchEvent(
      new MouseEvent("click", {
        view: window,
        bubbles: true,
        cancelable: true,
        clientX: x,
        clientY: y,
        screenX: window.screenX + x || x,
        screenY: window.screenY + y || y,
        button: 0,
        buttons: 0,
      })
    );
    setClickCounter((prev) => prev + 1);
  }, []);

  const getViewportRect = useCallback((rect: DOMRect): ViewportRect => {
    const left = Math.max(0, rect.left);
    const top = Math.max(0, rect.top);
    const right = Math.min(window.innerWidth, rect.right);
    const bottom = Math.min(window.innerHeight, rect.bottom);
    return {
      left,
      top,
      right,
      bottom,
      width: Math.max(0, right - left),
      height: Math.max(0, bottom - top),
    };
  }, []);

  const getButtonRectAtPoint = useCallback(
    (x: number, y: number): ViewportRect | null => {
      const pointedElement = document.elementFromPoint(x, y);
      const buttonElement =
        pointedElement instanceof Element
          ? pointedElement.closest(buttonSelector)
          : null;

      if (!(buttonElement instanceof HTMLElement)) return null;

      const rect = buttonElement.getBoundingClientRect();
      if (rect.width <= 0 || rect.height <= 0) return null;

      return getViewportRect(rect);
    },
    [getViewportRect]
  );

  const updateRecordingPointer = useCallback(
    (x: number, y: number) => {
      const pointer = { x: Math.round(x), y: Math.round(y) };
      setRecordingPointerPosition(pointer);
      setHoveredButtonRect(getButtonRectAtPoint(pointer.x, pointer.y));
    },
    [getButtonRectAtPoint]
  );

  // ---------- add/remove 监听器函数 ----------
  const addRecordingPointerListeners = useCallback(() => {
    document.addEventListener("mousemove", handleRecordingPointerMoveStable, {
      passive: true,
    });
    document.addEventListener("scroll", refreshRecordingPointerTargetStable, true);
    window.addEventListener("resize", refreshRecordingPointerTargetStable);
  }, [handleRecordingPointerMoveStable, refreshRecordingPointerTargetStable]);

  const removeRecordingPointerListeners = useCallback(() => {
    document.removeEventListener("mousemove", handleRecordingPointerMoveStable);
    document.removeEventListener("scroll", refreshRecordingPointerTargetStable, true);
    window.removeEventListener("resize", refreshRecordingPointerTargetStable);
  }, [handleRecordingPointerMoveStable, refreshRecordingPointerTargetStable]);

  const addRecordingClickListener = useCallback(
    (defer: boolean) => {
      if (recordingClickListenerTimerRef.current !== null) {
        window.clearTimeout(recordingClickListenerTimerRef.current);
        recordingClickListenerTimerRef.current = null;
      }

      if (!defer) {
        document.addEventListener("click", recordingListenerStable);
        return;
      }

      recordingClickListenerTimerRef.current = window.setTimeout(() => {
        recordingClickListenerTimerRef.current = null;
        if (isRecording) {
          document.addEventListener("click", recordingListenerStable);
        }
      }, 0);
    },
    [recordingListenerStable, isRecording]
  );

  const removeRecordingClickListener = useCallback(() => {
    if (recordingClickListenerTimerRef.current !== null) {
      window.clearTimeout(recordingClickListenerTimerRef.current);
      recordingClickListenerTimerRef.current = null;
    }
    document.removeEventListener("click", recordingListenerStable);
  }, [recordingListenerStable]);

  // ---------- 播放/录制控制 ----------
  const stopPlayback = useCallback(() => {
    if (intervalIdRef.current) {
      clearInterval(intervalIdRef.current);
      intervalIdRef.current = null;
    }
    setIsPlaying(false);
  }, []);

  const stopRecording = useCallback(() => {
    if (!isRecording) return;
    setIsRecording(false);
    removeRecordingClickListener();
    removeRecordingPointerListeners();
    setRecordingPointerPosition(null);
    setHoveredButtonRect(null);
  }, [isRecording, removeRecordingClickListener, removeRecordingPointerListeners]);

  const startPlayback = useCallback(() => {
    if (isPlaying) return;
    if (isRecording) {
      stopRecording();
    }
    if (recordedSteps.length === 0) return;

    setCurrentStepIndex(0);
    setIsPlaying(true);

    if (intervalIdRef.current) {
      clearInterval(intervalIdRef.current);
      intervalIdRef.current = null;
    }

    intervalIdRef.current = setInterval(playNextStepStable, intervalMs);
    playNextStepStable();
  }, [isPlaying, isRecording, recordedSteps.length, intervalMs, stopRecording, playNextStepStable]);

  const startRecording = useCallback(
    (e?: MouseEvent) => {
      if (isRecording) return;
      if (isPlaying) {
        stopPlayback();
      }

      setRecordedSteps([]);
      setCurrentStepIndex(0);
      setIsRecording(true);

      if (e) {
        updateRecordingPointer(e.clientX, e.clientY);
      }

      addRecordingClickListener(Boolean(e));
      addRecordingPointerListeners();
    },
    [
      isRecording,
      isPlaying,
      stopPlayback,
      updateRecordingPointer,
      addRecordingClickListener,
      addRecordingPointerListeners,
    ]
  );

  const toggleRecording = useCallback(
    (e?: MouseEvent) => {
      if (isRecording) {
        stopRecording();
      } else {
        startRecording(e);
      }
    },
    [isRecording, stopRecording, startRecording]
  );

  const onIntervalChange = useCallback(() => {
    setIntervalMs((prev) => {
      let next = prev;
      if (next < 50) next = 50;
      if (next > 10000) next = 10000;
      return next;
    });

    if (isPlaying) {
      stopPlayback();
      // 重启以应用新间隔（延迟一帧确保 state 已更新）
      requestAnimationFrame(() => playNextStepRef.current && startPlayback());
    }
  }, [isPlaying, stopPlayback, startPlayback]);

  const resetCounter = useCallback(() => {
    setClickCounter(0);
  }, []);

  // ---------- ref.current 赋值（每次渲染更新，访问最新 state） ----------
  playNextStepRef.current = () => {
    if (!isPlaying) return;
    if (recordedSteps.length === 0) {
      stopPlayback();
      return;
    }
    const step = recordedSteps[currentStepIndex];
    performClickAt(step.x, step.y);
    setCurrentStepIndex((prev) => {
      const next = prev + 1;
      return next >= recordedSteps.length ? 0 : next;
    });
  };

  recordingListenerRef.current = (e: MouseEvent) => {
    if (!isRecording) return;
    const x = e.clientX;
    const y = e.clientY;
    setRecordedSteps((prev) => [...prev, { x, y }]);
  };

  handleRecordingPointerMoveRef.current = (e: MouseEvent) => {
    if (!isRecording) return;
    updateRecordingPointer(e.clientX, e.clientY);
  };

  refreshRecordingPointerTargetRef.current = () => {
    if (!isRecording || !recordingPointerPosition) return;
    const { x, y } = recordingPointerPosition;
    setHoveredButtonRect(getButtonRectAtPoint(x, y));
  };

  handleKeydownRef.current = (e: KeyboardEvent) => {
    const isCtrl = e.ctrlKey || e.metaKey;
    const isShift = e.shiftKey;

    if (isCtrl && isShift && (e.key === "l" || e.key === "L")) {
      e.preventDefault();
      if (isRecording) {
        stopRecording();
      }
      if (isPlaying) {
        stopPlayback();
      } else {
        startPlayback();
      }
    }

    if (isCtrl && isShift && (e.key === "r" || e.key === "R")) {
      e.preventDefault();
      toggleRecording();
    }
  };

  // ---------- 生命周期 ----------
  useEffect(() => {
    document.addEventListener("keydown", handleKeydownStable);

    return () => {
      if (intervalIdRef.current) {
        clearInterval(intervalIdRef.current);
        intervalIdRef.current = null;
      }
      removeRecordingClickListener();
      removeRecordingPointerListeners();
      document.removeEventListener("keydown", handleKeydownStable);
    };
  }, [handleKeydownStable, removeRecordingClickListener, removeRecordingPointerListeners]);

  return (
    <>
      {/* 录制时的十字准线 overlay */}
      {isRecording && recordingPointerPosition && (
        <div className="recording-pointer-overlay" aria-hidden="true">
          {crosshairSegments.map((segment) => (
            <div
              key={segment.key}
              className={`recording-crosshair-line ${segment.className}`}
              style={segment.style}
            />
          ))}
          {hoveredButtonRect && (
            <div
              className="recording-button-outline"
              style={buttonOutlineStyle}
            />
          )}
          <div className="recording-coordinate-badge" style={coordinateBadgeStyle}>
            <span>clientX {recordingPointerPosition.x}</span>
            <span>clientY {recordingPointerPosition.y}</span>
          </div>
        </div>
      )}

      {/* 可拖拽的连点器卡片 */}
      <Draggable canOverflow={false}>
        <div
          className="auto-clicker-card"
          style={{ display: visible ? "block" : "none" }}
        >
          <h1>
            <span>🖱️ 连点器 · 统一间隔</span>
          </h1>
          <div className="subhead">
            录制点击序列 · 统一间隔控制 · 快捷键 <kbd>Ctrl+Shift+L</kbd> 切换播放
          </div>

          <div className="control-group">
            <label htmlFor="intervalInput">⏱️ 间隔 (ms)</label>
            <input
              id="intervalInput"
              type="number"
              min={50}
              max={10000}
              step={50}
              value={intervalMs}
              onChange={(e) => setIntervalMs(Number(e.target.value))}
              onBlur={onIntervalChange}
            />
            <span className="unit-label">ms</span>
          </div>

          <div className="btn-group">
            <button
              className="btn btn-primary"
              disabled={isPlaying || isRecording}
              onClick={startPlayback}
            >
              ▶ 播放
            </button>
            <button
              className="btn btn-danger"
              disabled={!isPlaying}
              onClick={stopPlayback}
            >
              ⏹ 停止
            </button>
            <button
              className={`btn btn-success ${isRecording ? "btn-recording" : ""}`}
              onClick={() => toggleRecording()}
            >
              {isRecording ? "⏹ 停止录制" : "🔴 录制"}
            </button>
            <button className="btn btn-outline" onClick={resetCounter}>
              ⟳ 重置计数
            </button>
          </div>

          <div className="delay-hint">
            <span>💡</span>
            <span>所有步骤使用统一的间隔时间，适合弹窗延迟较固定的场景</span>
          </div>

          <div className="status-box">
            <div className="status-indicator">
              <span className={`status-dot ${statusDotClass}`} />
              <span style={{ fontWeight: 450, color: "#1e2a44" }}>{statusText}</span>
              <span className="record-steps">步骤: {recordedSteps.length}</span>
            </div>
            <div className="click-counter">
              <span>点击</span>
              <span>{clickCounter}</span>
            </div>
          </div>

          <div className="footer-note">
            <span>⚡ 录制时点击页面任意位置记录坐标</span>
            <span>· 再次点击录制按钮结束</span>
          </div>
        </div>
      </Draggable>
    </>
  );
};

export default AutoClick;
