// extension/src/apps/sidebar/HoverMenu.tsx
/**
 * HoverMenu - 侧边悬浮菜单（React 版）
 *
 * 从 HoverMenu.vue 迁移而来。
 *
 * 关键变更：
 * - defineProps → React FC props
 * - ref → useRef
 * - emit('click') → props.onClick
 * - eventManager.useBus({ show, hide }) → bus.on('show'/'hide')
 *   注：原 Vue 代码传对象非 Map，实际未注册成功，React 版修正为正确注册
 * - eventManager.useListener('keydown', handler) → window.addEventListener('keydown')
 *   注：原 Vue 代码 target 传错（'keydown' 字符串），React 版修正为 window
 * - onMounted/onUnmounted → useEffect
 * - IconCommunity (?component) → Ant Design 图标（TeamOutlined）
 *
 * 保留的特性：
 * - dock 的 hover/active 状态切换动画
 * - miku-trigger 滑出动画
 * - 点击 trigger 切换 MikuChatWindow 显示
 *
 * @author Zero
 * @version v1.0.0
 * @license MIT
 */
import React, { useState, useRef, useEffect, useCallback } from "react";
import { TeamOutlined } from "@ant-design/icons";
import type { Tool } from "@/types";
import { bus } from "@/event/bus";
import MikuChatWindow from "./MikuChatWindow";
import "./styles/hover-menu.scss";

/** HoverMenu Props */
export interface HoverMenuProps {
  /** 菜单项列表 */
  items: Tool[];
  /** 布局方向（保留接口，当前未使用） */
  layout?: "vertical" | "horizontal" | "fold";
  /** 是否可见 */
  visible?: boolean;
  /** 点击菜单项回调 */
  onClick?: (item: Tool) => void;
}

/** 彩虹色数组（与原 Vue 版保持一致） */
const RAINBOW_COLORS = [
  "#FF0000",
  "#FF7F00",
  "#FFFF00",
  "#00FF00",
  "#0000FF",
  "#4B0082",
  "#9400D3",
];

/** 根据索引获取彩虹色 */
const getRainbowColor = (index: number): string =>
  RAINBOW_COLORS[index % RAINBOW_COLORS.length];

/**
 * 侧边悬浮菜单组件
 * - 包含 Miku trigger 图片和 dock 菜单容器
 * - 点击 trigger 切换 MikuChatWindow 显示
 * - 监听 bus 的 show/hide 事件控制 dock 的 active 状态
 * - 监听 Ctrl+Q 快捷键切换 dock 的 hover 状态
 */
const HoverMenu: React.FC<HoverMenuProps> = ({
  items,
  visible: initialVisible = true,
  onClick,
}) => {
  // 控制 dock 的 active 状态（用于触发 dock-cell 滑出动画）
  const [isActive, setIsActive] = useState(false);
  // Miku trigger 是否可见
  const [mikuTriggerVisible, setMikuTriggerVisible] = useState(false);
  // Miku 对话窗口是否可见
  const [mikuChatVisible, setMikuChatVisible] = useState(false);
  // 当前 hover 的菜单项索引（保留状态，用于未来扩展）
  const [hoverIdx, setHoverIdx] = useState(-1);

  const dockRef = useRef<HTMLDivElement>(null);

  // Miku 图片资源
  const mikuSrc = chrome.runtime.getURL("static/img/miku.png");

  // 显示整个菜单
  const show = useCallback(() => {
    dockRef.current?.classList.add("active");
    setIsActive(true);
  }, []);

  // 隐藏整个菜单
  const hide = useCallback(() => {
    dockRef.current?.classList.remove("active");
    setIsActive(false);
  }, []);

  // 切换 Miku 对话窗口
  const toggleMikuChat = useCallback(() => {
    setMikuTriggerVisible((prev) => !prev);
    setMikuChatVisible((prev) => !prev);
  }, []);

  // 鼠标进入菜单项
  const onMouseEnter = useCallback((index: number) => {
    setHoverIdx(index);
  }, []);

  // 鼠标离开菜单项
  const onMouseLeave = useCallback(() => {
    setHoverIdx(-1);
  }, []);

  // 点击菜单项
  const onClickItem = useCallback(
    (index: number) => {
      const item = items[index];
      onClick?.(item);
    },
    [items, onClick],
  );

  // 注册 bus 事件 + keydown 监听
  useEffect(() => {
    bus.on("show", show);
    bus.on("hide", hide);

    // 处理 Ctrl+Q 快捷键：切换 dock 的 hover 状态
    const handleKeyDown = (event: KeyboardEvent) => {
      maLogger.log("Key pressed:", event.key, "ctrlKey:", event.ctrlKey);
      if (event.ctrlKey && event.key.toLowerCase() === "q") {
        event.preventDefault();
        dockRef.current?.classList.toggle("hover");
      }
    };
    window.addEventListener("keydown", handleKeyDown);

    return () => {
      bus.off("show", show);
      bus.off("hide", hide);
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [show, hide]);

  // 模拟 Vue onMounted：先显示 trigger，100ms 后 show，500ms 后 hide
  useEffect(() => {
    setMikuTriggerVisible(true);

    const showTimer = window.setTimeout(() => {
      show();
    }, 100);

    const hideTimer = window.setTimeout(() => {
      hide();
    }, 500);

    return () => {
      window.clearTimeout(showTimer);
      window.clearTimeout(hideTimer);
    };
  }, [show, hide]);

  return (
    <>
      <div
        ref={dockRef}
        className={`dock ${isActive ? "active" : ""}`}
        style={{ position: "fixed", right: 0, top: "50%" }}
      >
        {mikuTriggerVisible && (
          <div
            className="miku-trigger"
            aria-label="打开 Miku 对话"
            style={{
              position: "absolute",
              right: "-84px",
              width: "126px",
              height: "auto",
            }}
            onClick={(e) => {
              e.stopPropagation();
              toggleMikuChat();
            }}
          >
            <img
              src={mikuSrc}
              alt="Miku trigger"
              aria-hidden="true"
              width="100%"
            />
          </div>
        )}

        {/* 菜单项列表（保留原 Vue 模板注释中的结构） */}
        {items.map((it, i) => (
          <li
            key={it.id}
            className="dock-cell"
            onMouseEnter={() => onMouseEnter(i)}
            onMouseLeave={onMouseLeave}
            onClick={() => onClickItem(i)}
            style={{ ["--delay" as string]: `${i * 0.12}s` }}
          >
            <div
              className={`dock-icon ${hoverIdx === i ? "hover" : ""}`}
              style={{ ["--c" as string]: it.color || getRainbowColor(i) }}
            >
              <TeamOutlined className="ic" />
            </div>
            {hoverIdx === i && it.label && (
              <div className="tip">{it.label}</div>
            )}
          </li>
        ))}
      </div>

      {mikuChatVisible && <MikuChatWindow onClose={toggleMikuChat} />}
    </>
  );
};

export default HoverMenu;

// extension/src/apps/sidebar/HoverMenu.vue
<template>
  <!-- 只在expanded为true时显示整个菜单容器 -->
  <div class="dock" ref="dockRef" style="position: fixed; right: 0;top:50%;">
    <div
      v-show="mikuTriggerVisible"
      class="miku-trigger"
      aria-label="打开 Miku 对话"
      @click.stop="toggleMikuChat"
      style="position: absolute; right: -84px; width: 126px; height: auto"
    >
      <img :src="mikuSrc" alt="Miku trigger" aria-hidden="true" width="100%"/>
    </div>
    <!-- <li
      v-for="(it, i) in items"
      :key="it.id"
      class="dock-cell"
      @mouseenter="onMouseEnter(i)"
      @mouseleave="onMouseLeave()"
      @click="onClick(i)"
      :style="{ '--delay': i * 0.12 + 's' }"
    >
      <div
        class="dock-icon"
        :class="{ hover: hoverIdx === i }"
        :style="{ '--c': it.color || getRainbowColor(i) }"
      >
        <component :is="it.icon || IconCommunity" class="ic" />
      </div>
      <div v-if="hoverIdx === i && it.label" class="tip">{{ it.label }}</div>
    </li> -->
  </div>
  <MikuChatWindow v-if="mikuChatVisible" @close="toggleMikuChat" />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from "vue";
import { Tool } from "@/types";
import { IconCommunity } from "@icons/index";
import { eventManager } from "@/event";
import MikuChatWindow from "./MikuChatWindow.vue";

// Props定义
const props = defineProps<{
  items: Tool[];
  layout?: "vertical" | "horizontal" | "fold";
  visible?: boolean;
}>();

// 彩虹色数组
const rainbowColors = [
  "#FF0000", // 红色
  "#FF7F00", // 橙色
  "#FFFF00", // 黄色
  "#00FF00", // 绿色
  "#0000FF", // 蓝色
  "#4B0082", // 靛蓝色
  "#9400D3", // 紫色
];

// 根据索引获取彩虹色
const getRainbowColor = (index: number) => {
  // 使用模运算确保索引不会超出数组范围
  return rainbowColors[index % rainbowColors.length];
};

const hoverIdx = ref<number>(-1); // 用于控制悬浮效果和提示文本
const mikuTriggerVisible = ref(false);
const mikuChatVisible = ref(false);

const mikuSrc = chrome.runtime.getURL("static/img/miku.png");

// 鼠标进入一级菜单 - 控制悬浮效果和提示文本
const onMouseEnter = (i: number) => {
  hoverIdx.value = i;
};

const onMouseLeave = () => {
  hoverIdx.value = -1;
};

const emit = defineEmits<{
  click: [item: Tool];
}>();

const toggleMikuChat = () => {
  mikuTriggerVisible.value = !mikuTriggerVisible.value;
  mikuChatVisible.value = !mikuChatVisible.value;
};

// 点击一级菜单 - 控制子菜单显示
const onClick = (i: number) => {
  const item = props.items[i];
  // 发出点击事件
  emit("click", item);
  // 点击已经激活的菜单项，不做任何操作
  if (hoverIdx.value === i) {
    return;
  }
};

const dockRef = ref<HTMLDivElement>();

// 显示整个菜单
const show = () => {
  dockRef.value?.classList.add("active");
};

// 隐藏整个菜单
const hide = () => {
  dockRef.value?.classList.remove("active");
};

// 处理键盘事件 - 监听Ctrl+Q快捷键
const handleKeyDown = (event: KeyboardEvent) => {
  // 添加调试日志
  maLogger.log("Key pressed:", event.key, "ctrlKey:", event.ctrlKey);
  // 检查是否按下了Ctrl+Q
  if (event.ctrlKey && event.key.toLowerCase() === "q") {
    // 阻止默认行为
    event.preventDefault();
    // 显示菜单
    dockRef.value?.classList.toggle("hover");
  }
};

eventManager.useBus({ show: show, hide: hide });
eventManager.useListener("keydown", handleKeyDown);

// 组件生命周期
onMounted(() => {
  mikuTriggerVisible.value = true;
  setTimeout(() => {
    show();
  }, 100);

  setTimeout(() => {
    hide();
  }, 500);
});
</script>

<style scoped lang="scss">
$dock-z-index: 9999;
$dock-border-radius: 10px;
$icon-size: 40px;
$icon-border-radius: 20px;
$trigger-width: 126px;
$trigger-offset: 84px;

.dock {
  position: fixed;
  right: 0;
  top: 50%;
  transform: translateY(-50%);
  display: flex;
  flex-direction: column;
  gap: 8px;
  z-index: $dock-z-index;
  opacity: 1;
  transition: opacity 0.6s ease;

  &::before {
    content: "";
    position: absolute;
    right: 0;
    top: 50%;
    transform: translateY(-50%);
    width: 28px;
    min-height: 144px;
    height: calc(100% + 32px);
    background: transparent;
    border-radius: $dock-border-radius 0 0 $dock-border-radius;
    cursor: pointer;
    z-index: 1;
  }
}

.miku-trigger {
  position: absolute;
  right: -$trigger-offset;
  top: 50%;
  width: 126px;
  height: auto;
  padding: 0;
  border: none;
  background: transparent;
  transform: translateY(-50%);
  transition:
    transform 0.32s cubic-bezier(0.22, 0.61, 0.36, 1),
    filter 0.2s ease;
  cursor: pointer;
  z-index: 2;
  filter: drop-shadow(0 8px 18px rgba(15, 23, 42, 0.24));
  will-change: transform, opacity;

  img {
    width: 100%;
    height: 100%;
    user-select: none;
    -webkit-user-drag: none;
    object-fit: cover; /* 或 contain，按需调整 */
    display: block;
  }

  &:focus-visible {
    outline: 2px solid rgba(37, 99, 235, 0.85);
    outline-offset: 3px;
    border-radius: 8px;
  }
}

.dock:hover .miku-trigger,
.dock.active .miku-trigger {
  transform: translate(calc(-#{$trigger-offset} + 1px), -50%);
}

.dock-cell {
  display: flex;
  position: relative;
  flex-direction: row-reverse;
  align-items: flex-start;
  right: -50px;
  transform: translateX(0);
  opacity: 1;
  transition:
    transform 0.3s ease,
    opacity 0.3s ease;
  z-index: 0;
  transition-delay: var(--delay, 0s);
}

.dock:hover .dock-cell,
.dock.active .dock-cell {
  transform: translateX(-120%);
}

.dock-icon {
  width: $icon-size;
  height: $icon-size;
  background: var(--c, #409eff);
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition:
    transform 0.25s cubic-bezier(0.25, 0.8, 0.25, 1),
    filter 0.25s;
  filter: drop-shadow(0 2px 8px rgba(0, 0, 0, 0.15));
  position: relative;
  border-radius: $icon-border-radius 0 0 $icon-border-radius;

  &.active,
  &:hover {
    transform: scaleX(1.35) scaleY(1.15);
    filter: drop-shadow(0 4px 12px rgba(0, 0, 0, 0.2));

    + .tip {
      opacity: 1;
    }
  }
}

.ic {
  width: 20px;
  height: 20px;
}

.tip {
  position: absolute;
  right: 110%;
  top: 50%;
  transform: translateY(-50%);
  padding: 4px 8px;
  background: rgba(0, 0, 0, 0.75);
  color: #fff;
  font-size: 12px;
  white-space: nowrap;
  border-radius: 4px;
  pointer-events: none;
  opacity: 0;
  transition: opacity 0.2s ease;
}

.arr {
  position: absolute;
  right: 4px;
  top: 50%;
  transform: translateY(-50%);
  font-size: 10px;
  opacity: 0.8;
}

@media (prefers-reduced-motion: reduce) {
  .dock,
  .dock-cell,
  .dock-icon,
  .miku-trigger,
  .tip {
    transition-duration: 0.01ms;
  }
}
</style>
