// extension/src/components/MagneticPointer.vue
<template>
    <div ref="pointer" class="pointer" :style="mouseStyle">
        <template v-for="(_, index) in 4" :key="index">
            <i class="corner" />
        </template>
    </div>
    <div class="content">
        <p class="_target">HOVER ME</p>
        <p class="_target">鼠标位置: {{ x }} {{ y }}</p>
    </div>

</template>

<script setup lang="ts">
import { ref, computed, onMounted, useTemplateRef } from 'vue';
import { useMouseTracker } from '@/composables/mouse/mouseTracker';

export interface PointerProps {
    color?: string
    size?: string
    cssSelector?: string[]
}

const props = withDefaults(defineProps<PointerProps>(), {
  color: '#1ff700',
  size: '4rem'
});

const { x, y } = useMouseTracker();
const currentElement = ref<HTMLElement | null>(null);
const pointerRef = useTemplateRef<HTMLElement>('pointer');

const mouseStyle = computed(() => {
  let newX = x.value;
  let newY = y.value;
  if (currentElement.value) {
    const rect = currentElement.value.getBoundingClientRect();
    const centerX = rect.left + rect.width / 2;
    const centerY = rect.top + rect.height / 2;
    newX = centerX + (x.value - centerX) * 0.1;
    newY = centerY + (y.value - centerY) * 0.1;
  }
  return {
    '--x': `${newX}px`,
    '--y': `${newY}px`
  };
});

onMounted(() => {
  const targetElements = [...document.querySelectorAll<HTMLElement>(props.cssSelector?.join(',') || '._target')];
  console.log(targetElements);
  if (props.color) {
        pointerRef.value!.style.setProperty('--color', props.color);
  }
  if (props.size) {
        pointerRef.value!.style.setProperty('--width', props.size);
        pointerRef.value!.style.setProperty('--height', props.size);
  }
  targetElements.forEach(item => {
    item.addEventListener('mouseenter', () => {
      const rect = item.getBoundingClientRect();
      currentElement.value = item;
            pointerRef.value!.style.setProperty('--width', rect.width + innerWidth * 0.02 + 'px');
            pointerRef.value!.style.setProperty('--height', rect.height + innerHeight * 0.02 + 'px');
    });
    item.addEventListener('mouseleave', () => {
      currentElement.value = null;
            pointerRef.value!.style.setProperty('--width', '4rem');
            pointerRef.value!.style.setProperty('--height', '4rem');
    });
  });
});
</script>

<style scoped lang="less">
p {
    color: #fff;
    font-size: 2rem;
    font-family: 'Courier New', Courier, monospace;
}

.content {
    position: absolute;
    display: flex;
    flex-direction: column;
    align-items: center;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

._target {
    width: auto;
    height: auto;
    color: rgb(255, 255, 255);
}

.pointer {
    --x: 0;
    --y: 0;
    --width: 4rem;
    --height: 4rem;
    --color: #1ff700;
    margin-left: calc(var(--width) / -2);
    margin-top: calc(var(--height) / -2);
    left: 0;
    top: 0;
    width: var(--width);
    height: var(--height);
    position: fixed;
    transform: translate(var(--x), var(--y));
    transition: all 0.2s ease-out;
    pointer-events: none;

    .corner {
        position: absolute;
        width: 1rem;
        height: 1rem;
        border: 0.3rem solid var(--color);
    }

    .corner:nth-child(1) {
        left: 0;
        top: 0;
        border-right: none;
        border-bottom: none;
    }

    .corner:nth-child(2) {
        right: 0;
        bottom: 0;
        border-top: none;
        border-left: none;
    }

    .corner:nth-child(3) {
        left: 0;
        bottom: 0;
        border-top: none;
        border-right: none;
    }

    .corner:nth-child(4) {
        right: 0;
        top: 0;
        border-left: none;
        border-bottom: none;
    }
}
</style>

// extension/src/components/MagneticPointer.tsx
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import "./magneticPointer.scss";

export interface MagneticPointerProps {
  color?: string;
  size?: string;
  cssSelector?: string[];
  hideUntilTargetHover?: boolean;
  children?: React.ReactNode;
}

const MagneticPointer = ({
  color = "#1ff700",
  size = "4rem",
  cssSelector,
  hideUntilTargetHover = false,
  children,
}: MagneticPointerProps) => {
  const pointerRef = useRef<HTMLDivElement>(null);
  const [portalTarget, setPortalTarget] = useState<HTMLElement | null>(null);
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const [currentElement, setCurrentElement] = useState<HTMLElement | null>(null);

  useEffect(() => {
    setPortalTarget(document.body);
  }, []);

  useEffect(() => {
    if (!portalTarget) return;
    const pointer = pointerRef.current;
    if (!pointer) return;

    pointer.style.setProperty("--color", color);
    pointer.style.setProperty("--width", size);
    pointer.style.setProperty("--height", size);

    const targets = document.querySelectorAll<HTMLElement>(
      cssSelector?.join(",") || "._target",
    );
    const handleMouseEnter = (event: Event) => {
      const target = event.currentTarget as HTMLElement;
      const rect = target.getBoundingClientRect();
      setCurrentElement(target);
      pointer.style.setProperty(
        "--width",
        `${rect.width + window.innerWidth * 0.02}px`,
      );
      pointer.style.setProperty(
        "--height",
        `${rect.height + window.innerHeight * 0.02}px`,
      );
    };
    const handleMouseLeave = () => {
      setCurrentElement(null);
      pointer.style.setProperty("--width", size);
      pointer.style.setProperty("--height", size);
    };

    targets.forEach((target) => {
      target.addEventListener("mouseenter", handleMouseEnter);
      target.addEventListener("mouseleave", handleMouseLeave);
    });

    return () => {
      targets.forEach((target) => {
        target.removeEventListener("mouseenter", handleMouseEnter);
        target.removeEventListener("mouseleave", handleMouseLeave);
      });
    };
  }, [color, cssSelector, portalTarget, size]);

  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      setMousePosition({ x: event.clientX, y: event.clientY });
    };

    window.addEventListener("mousemove", handleMouseMove);
    return () => window.removeEventListener("mousemove", handleMouseMove);
  }, []);

  let pointerX = mousePosition.x;
  let pointerY = mousePosition.y;
  if (currentElement) {
    const rect = currentElement.getBoundingClientRect();
    const centerX = rect.left + rect.width / 2;
    const centerY = rect.top + rect.height / 2;
    pointerX = centerX + (mousePosition.x - centerX) * 0.1;
    pointerY = centerY + (mousePosition.y - centerY) * 0.1;
  }

  return (
    <>
      {portalTarget &&
        createPortal(
      <div
        ref={pointerRef}
        className="magnetic-pointer"
        style={
          {
            "--x": `${pointerX}px`,
            "--y": `${pointerY}px`,
            visibility:
              hideUntilTargetHover && !currentElement ? "hidden" : undefined,
          } as React.CSSProperties
        }
        aria-hidden="true"
      >
        {Array.from({ length: 4 }, (_, index) => (
          <i className="magnetic-pointer__corner" key={index} />
        ))}
      </div>
        , portalTarget)}
      <div className="magnetic-pointer__content">
        {children ?? (
          <>
            <p className="_target">HOVER ME</p>
            <p className="_target">
              鼠标位置: {mousePosition.x} {mousePosition.y}
            </p>
          </>
        )}
      </div>
    </>
  );
};

export default MagneticPointer;
