// extension/src/assets/components/TextScramble.vue
<template>
    <div class="container">
        <div ref="textEl" class="text"></div>
    </div>
</template>

<script setup lang="ts">
import { useTemplateRef, onMounted } from 'vue';

// 定义props
const props = defineProps({
  phrases: {
    type: Array < string >,
    default: () => [
      'Neo,',
      'sooner or later',
      'you\'re going to realize',
      'just as I did',
      'that there\'s a difference',
      'between knowing the path',
      'and walking the path'
    ]
  },
  chars: {
    type: String,
    default: '!<>-_\\/[]{}?=+*^?#________'
  },
  speed: {
    type: Number,
    default: 800
  }
});

class TextScramble {
  _el: HTMLElement | null;
  _chars: string;
  _resolve: ((value?: any) => void) | null = null;
  queue: { from: string; to: string; start: number; end: number; char?: string }[] = [];
  frame: number = 0;
  frameRequest: number | null = null;
  constructor(el: HTMLElement | null, chars?: string) {
    this._el = el;
    this._chars = chars || '!<>-_\/[]{}?=+*^?#________';
    this.update = this.update.bind(this);
  }
  setText(newText: string) {
    const oldText = this._el!.innerText;
    const length = Math.max(oldText.length, newText.length);
    const promise = new Promise(resolve => this._resolve = resolve);
    this.queue = [];
    for (let i = 0; i < length; i++) {
      const from = oldText[i] || '';
      const to = newText[i] || '';
      const start = Math.floor(Math.random() * 40);
      const end = start + Math.floor(Math.random() * 40);
      this.queue.push({ from, to, start, end });
    }
    cancelAnimationFrame(this.frameRequest!);
    this.frame = 0;
    this.update();
    return promise;
  }
  private update() {
    let output = '';
    let complete = 0;
    for (let i = 0, n = this.queue.length; i < n; i++) {
      let { from, to, start, end, char } = this.queue[i];
      if (this.frame >= end) {
        complete++;
        output += to;
      } else if (this.frame >= start) {
        if (!char || Math.random() < 0.28) {
          char = this.randomChar();
          this.queue[i].char = char;
        }
        output += `<span class="dud">${char}</span>`;
      } else {
        output += from;
      }
    }
        this._el!.innerHTML = output;
        if (complete === this.queue.length) {
            this._resolve!();
        } else {
          this.frameRequest = requestAnimationFrame(this.update);
          this.frame++;
        }
  }
  randomChar() {
    return this._chars[Math.floor(Math.random() * this._chars.length)];
  }
}

onMounted(() => {
  const el = document.querySelector < HTMLElement > ('.text');
  maLogger.log(el);
  const fx = new TextScramble(el, props.chars);

  let counter = 0;
  const next = () => {
    fx.setText(props.phrases[counter]).then(() => {
      setTimeout(next, props.speed);
    });
    counter = (counter + 1) % props.phrases.length;
  };

  next();
});
</script>

<style scoped>
@import 'https://fonts.googleapis.com/css?family=Roboto+Mono:100';

html,
body {
    font-family: 'Roboto Mono', monospace;
    background: #212121;
    height: 100%;
}

.container {
    height: 100%;
    width: 100%;
    justify-content: center;
    align-items: center;
    display: flex;
}

.text {
    font-weight: 100;
    font-size: 28px;
    color: #fafafa;
}

.dud {
    color: #757575;
}
</style>

// extension/src/components/TextScramble.tsx
import { useEffect, useState } from "react";
import "./TextScramble.scss";

export interface TextScrambleProps {
  phrases?: string[];
  chars?: string;
  speed?: number;
  className?: string;
}

export const DEFAULT_TEXT_SCRAMBLE_PHRASES = [
  "Neo,",
  "sooner or later",
  "you're going to realize",
  "just as I did",
  "that there's a difference",
  "between knowing the path",
  "and walking the path",
];

interface ScrambleCharacter {
  value: string;
  isScrambled: boolean;
}

const DEFAULT_CHARS = "!<>-_\\/[]{}?=+*^?#________";

const TextScramble = ({
  phrases = DEFAULT_TEXT_SCRAMBLE_PHRASES,
  chars = DEFAULT_CHARS,
  speed = 800,
  className = "",
}: TextScrambleProps) => {
  const [renderedCharacters, setRenderedCharacters] = useState<ScrambleCharacter[]>([]);

  useEffect(() => {
    if (phrases.length === 0) {
      setRenderedCharacters([]);
      return;
    }

    let disposed = false;
    let frame = 0;
    let frameRequest: number | undefined;
    let delayTimeout: number | undefined;
    let currentText = "";
    let phraseIndex = 0;
    const alphabet = chars || DEFAULT_CHARS;

    const animateTo = (nextText: string) => {
      const fromCharacters = Array.from(currentText);
      const targetCharacters = Array.from(nextText);
      const queue = Array.from(
        { length: Math.max(fromCharacters.length, targetCharacters.length) },
        (_, index) => {
          const start = Math.floor(Math.random() * 40);
          return {
            from: fromCharacters[index] ?? "",
            to: targetCharacters[index] ?? "",
            start,
            end: start + Math.floor(Math.random() * 40),
            randomCharacter: "",
          };
        },
      );

      frame = 0;
      const update = () => {
        if (disposed) return;
        let complete = 0;
        const nextCharacters = queue.map((character) => {
          if (frame >= character.end) {
            complete += 1;
            return { value: character.to, isScrambled: false };
          }
          if (frame >= character.start) {
            if (!character.randomCharacter || Math.random() < 0.28) {
              character.randomCharacter =
                alphabet[Math.floor(Math.random() * alphabet.length)];
            }
            return { value: character.randomCharacter, isScrambled: true };
          }
          return { value: character.from, isScrambled: false };
        });

        setRenderedCharacters(nextCharacters);
        if (complete === queue.length) {
          currentText = nextText;
          delayTimeout = window.setTimeout(() => {
            phraseIndex = (phraseIndex + 1) % phrases.length;
            animateTo(phrases[phraseIndex]);
          }, Math.max(0, speed));
          return;
        }

        frame += 1;
        frameRequest = window.requestAnimationFrame(update);
      };

      update();
    };

    animateTo(phrases[phraseIndex]);

    return () => {
      disposed = true;
      if (frameRequest !== undefined) window.cancelAnimationFrame(frameRequest);
      if (delayTimeout !== undefined) window.clearTimeout(delayTimeout);
    };
  }, [phrases, chars, speed]);

  return (
    <div className={`text-scramble ${className}`.trim()}>
      <div className="text-scramble__text" aria-live="off">
        {renderedCharacters.map((character, index) => (
          <span
            className={character.isScrambled ? "text-scramble__dud" : undefined}
            key={`${index}-${character.value}`}
          >
            {character.value}
          </span>
        ))}
      </div>
    </div>
  );
};

export default TextScramble;
