// extension/src/apps/floatingball/views/ScriptRunner.tsx
/**
 * ScriptRunner.tsx - React 版脚本执行工具
 * 从 Vue 版 ScriptRunner.vue 迁移而来
 *
 * 功能：支持代码输入、文件上传、网络脚本三种方式执行 JavaScript
 *
 * @author Zero
 * @version v1.0.0
 * @license MIT
 */
import React, { useState, useCallback } from "react";
import { Button, Tabs, Input, Upload } from "antd";
import type { UploadProps } from "antd";
import {
  PlayCircleOutlined,
  LoadingOutlined,
  DeleteOutlined,
  CopyOutlined,
  EditOutlined,
  UploadOutlined,
  FileTextOutlined,
  LinkOutlined,
  DownloadOutlined,
  CheckCircleOutlined,
  DesktopOutlined,
} from "@ant-design/icons";
import { injectScriptToActivateTab } from "@/utils/element-control";
import message from "@/message/index.js";
import "./styles/script-runner.scss";

/** Tab 类型（替代原 TabPaneName）*/
type TabKey = "code" | "file" | "url";

/** 通知消息类型 */
interface NotificationMessage {
  message: string;
  type: "success" | "info" | "warning" | "error";
}

interface ScriptRunnerProps {
  /** 添加通知消息回调（对应原 emit('add-message')）*/
  onAddMessage?: (msg: NotificationMessage) => void;
}

const { TextArea } = Input;

/**
 * ScriptRunner - 脚本执行工具
 */
const ScriptRunner: React.FC<ScriptRunnerProps> = ({ onAddMessage }) => {
  const [activeTab, setActiveTab] = useState<TabKey>("code");
  const [scriptCode, setScriptCode] = useState("");
  const [outputText, setOutputText] = useState("");
  const [running, setRunning] = useState(false);
  const [scriptUrl, setScriptUrl] = useState("");
  const [fileInfo, setFileInfo] = useState<{ name: string; size: number } | null>(null);
  const [urlInfo, setUrlInfo] = useState<{ url: string } | null>(null);

  const ext = message.ext;

  /**
   * 执行脚本
   */
  const executeScript = useCallback(async () => {
    let codeToExecute = "";

    switch (activeTab) {
      case "code":
        if (!scriptCode.trim()) {
          onAddMessage?.({ message: "请输入JavaScript代码", type: "warning" });
          return;
        }
        codeToExecute = scriptCode;
        break;
      case "file":
        if (!fileInfo) {
          onAddMessage?.({ message: "请选择本地JavaScript文件", type: "warning" });
          return;
        }
        codeToExecute = scriptCode;
        break;
      case "url":
        if (!urlInfo) {
          onAddMessage?.({ message: "请加载网络脚本", type: "warning" });
          return;
        }
        codeToExecute = scriptCode;
        break;
    }

    setRunning(true);
    setOutputText("");

    try {
      // 直接执行脚本
      injectScriptToActivateTab({ scriptStr: codeToExecute });

      // 显示执行成功信息
      setOutputText("脚本已开始执行，请在控制台查看输出");
      onAddMessage?.({ type: "success", message: "脚本执行开始" });
    } catch (error: any) {
      // 捕获执行错误
      setOutputText(`执行错误: ${error.message}\n${error.stack || ""}`);
      onAddMessage?.({ type: "error", message: "脚本执行出错" });
    } finally {
      setRunning(false);
    }
  }, [activeTab, scriptCode, fileInfo, urlInfo, onAddMessage]);

  /**
   * 清空脚本
   */
  const clearScript = useCallback(() => {
    setScriptCode("");
    setOutputText("");
    setFileInfo(null);
    setUrlInfo(null);
    setScriptUrl("");
    onAddMessage?.({ type: "info", message: "已清空" });
  }, [onAddMessage]);

  /**
   * 复制结果
   */
  const copyResult = useCallback(() => {
    if (outputText) {
      navigator.clipboard
        .writeText(outputText)
        .then(() => {
          onAddMessage?.({ type: "success", message: "结果已复制到剪贴板" });
        })
        .catch(() => {
          onAddMessage?.({ type: "error", message: "复制失败" });
        });
    }
  }, [outputText, onAddMessage]);

  /**
   * 处理文件选择
   */
  const handleFileChange: UploadProps["onChange"] = useCallback(
    (info) => {
      const selectedFile = info.file?.originFileObj;
      if (selectedFile) {
        const reader = new FileReader();
        reader.onload = (e: ProgressEvent<FileReader>) => {
          setScriptCode(e.target?.result as string);
          setFileInfo({
            name: selectedFile.name,
            size: selectedFile.size,
          });
          onAddMessage?.({ type: "success", message: "文件读取成功" });
        };
        reader.onerror = () => {
          onAddMessage?.({ type: "error", message: "文件读取失败" });
        };
        reader.readAsText(selectedFile);
      }
    },
    [onAddMessage]
  );

  /**
   * 清除文件
   */
  const clearFile = useCallback(() => {
    setFileInfo(null);
    setScriptCode("");
  }, []);

  /**
   * 加载网络脚本
   */
  const loadUrlScript = useCallback(async () => {
    if (!scriptUrl.trim()) {
      onAddMessage?.({ type: "warning", message: "请输入网络脚本URL" });
      return;
    }

    setRunning(true);

    try {
      // 使用脚本执行服务加载网络脚本，绕过 CORS 限制
      const response = await ext.send({
        type: "LOAD_URL_SCRIPT",
        payload: { url: scriptUrl },
        target: "background",
      });

      if (!response.success) {
        throw new Error(response.error || "加载网络脚本失败");
      }

      const scriptContent = response.result;
      maLogger.log("加载的网络脚本内容:", scriptContent);
      setScriptCode(scriptContent);
      setUrlInfo({ url: scriptUrl });
      onAddMessage?.({ type: "success", message: "网络脚本加载成功" });
    } catch (error: any) {
      onAddMessage?.({
        type: "error",
        message: `网络脚本加载失败: ${error.message}`,
      });
    } finally {
      setRunning(false);
    }
  }, [scriptUrl, ext, onAddMessage]);

  /**
   * 清除 URL
   */
  const clearUrl = useCallback(() => {
    setUrlInfo(null);
    setScriptUrl("");
    setScriptCode("");
  }, []);

  // Tab 项配置（antd items API）
  const tabItems = [
    {
      key: "code",
      label: "代码输入",
      children: (
        <div className="script-input-container">
          <div className="section-header">
            <EditOutlined />
            <span>JavaScript代码</span>
          </div>
          <div className="code-editor">
            <textarea
              value={scriptCode}
              onChange={(e) => setScriptCode(e.target.value)}
              placeholder={`在这里输入JavaScript代码...\n\n// 可以访问当前页面的DOM\n// 示例: maLogger.log('Hello World!');\n// 示例: document.title = '修改后的标题';`}
              rows={10}
              readOnly={running}
            />
          </div>
        </div>
      ),
    },
    {
      key: "file",
      label: "文件上传",
      children: (
        <div className="file-upload-container">
          <div className="section-header">
            <UploadOutlined />
            <span>本地脚本文件</span>
          </div>
          <div className="upload-area">
            <Upload
              beforeUpload={() => false}
              onChange={handleFileChange}
              showUploadList={false}
              accept=".js"
            >
              <Button type="primary">
                <UploadOutlined /> 选择JS文件
              </Button>
            </Upload>
            {fileInfo ? (
              <div className="file-info">
                <FileTextOutlined />
                <span>{fileInfo.name}</span>
                <Button size="small" type="link" onClick={clearFile}>
                  清除
                </Button>
              </div>
            ) : (
              <div className="upload-hint">请选择本地JavaScript文件</div>
            )}
          </div>
        </div>
      ),
    },
    {
      key: "url",
      label: "网络脚本",
      children: (
        <div className="url-script-container">
          <div className="section-header">
            <LinkOutlined />
            <span>网络脚本URL</span>
          </div>
          <div className="url-input-area">
            <Input
              value={scriptUrl}
              onChange={(e) => setScriptUrl(e.target.value)}
              placeholder="输入网络脚本URL..."
              disabled={running}
              addonAfter={
                <Button
                  size="small"
                  type="link"
                  disabled={!scriptUrl || running}
                  onClick={loadUrlScript}
                  style={{ padding: 0 }}
                >
                  <DownloadOutlined /> 加载
                </Button>
              }
            />
            {urlInfo ? (
              <div className="url-info">
                <CheckCircleOutlined />
                <span>已加载: {urlInfo.url}</span>
                <Button size="small" type="link" onClick={clearUrl}>
                  清除
                </Button>
              </div>
            ) : scriptUrl ? (
              <div className="url-hint">点击加载按钮获取脚本内容</div>
            ) : (
              <div className="url-hint">请输入网络脚本URL</div>
            )}
          </div>
        </div>
      ),
    },
  ];

  return (
    <div className="script-runner">
      <header>
        <h1>
          <FileTextOutlined /> 自动化工具
        </h1>
      </header>

      <div className="content">
        {/* 控制面板 */}
        <div className="control-panel">
          <div className="control-buttons">
            <Button
              type="primary"
              loading={running}
              icon={running ? <LoadingOutlined /> : <PlayCircleOutlined />}
              onClick={executeScript}
            >
              {running ? "执行中..." : "执行脚本"}
            </Button>
            <Button icon={<DeleteOutlined />} onClick={clearScript}>
              清空
            </Button>
            <Button
              icon={<CopyOutlined />}
              disabled={!outputText}
              onClick={copyResult}
            >
              复制结果
            </Button>
          </div>
        </div>

        {/* 标签页切换 */}
        <div className="tab-container">
          <Tabs
            activeKey={activeTab}
            onChange={(key) => setActiveTab(key as TabKey)}
            items={tabItems}
          />
        </div>

        {/* 输出结果区域 */}
        <div className="output-container">
          <div className="section-header">
            <DesktopOutlined />
            <span>执行结果</span>
          </div>
          <div className="output-content">
            {outputText ? (
              <pre className="output-text">{outputText}</pre>
            ) : (
              <div className="no-output">暂无输出</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

ScriptRunner.displayName = "ScriptRunner";

export default ScriptRunner;
// 重新导出类型供其他模块使用
export type { ScriptRunnerProps, TabKey };

// extension/src/apps/floatingball/views/ScriptRunner.vue
<template>
  <div class="script-runner">
    <header>
      <h1><el-icon class="el-icon-document"></el-icon>自动化工具</h1>
    </header>

    <div class="content">
      <!-- 控制面板 -->
      <div class="control-panel">
        <div class="control-buttons">
          <el-button type="primary" :loading="running" @click="executeScript">
            <el-icon v-if="!running" class="el-icon-play"></el-icon>
            <el-icon v-else class="el-icon-loading"></el-icon>
            {{ running ? '执行中...' : '执行脚本' }}
          </el-button>
          <el-button @click="clearScript">
            <el-icon class="el-icon-delete"></el-icon> 清空
          </el-button>
          <el-button :disabled="!outputText" @click="copyResult">
            <el-icon class="el-icon-copy-document"></el-icon> 复制结果
          </el-button>
        </div>
      </div>

      <!-- 标签页切换 -->
      <div class="tab-container">
        <el-tabs v-model="activeTab" @tab-change="handleTabChange">
          <el-tab-pane label="代码输入" name="code">
            <div class="script-input-container">
              <div class="section-header">
                <el-icon class="el-icon-edit"></el-icon>
                <span>JavaScript代码</span>
              </div>
              <div class="code-editor">
                <textarea v-model="scriptCode"
                  placeholder="在这里输入JavaScript代码...\n\n// 可以访问当前页面的DOM\n// 示例: maLogger.log('Hello World!');\n// 示例: document.title = '修改后的标题';"
                  rows="10" :readonly="running"></textarea>
              </div>
            </div>
          </el-tab-pane>
          <el-tab-pane label="文件上传" name="file">
            <div class="file-upload-container">
              <div class="section-header">
                <el-icon class="el-icon-upload"></el-icon>
                <span>本地脚本文件</span>
              </div>
              <div class="upload-area">
                <el-upload class="upload-demo" action="" :auto-upload="false" :on-change="handleFileChange"
                  :show-file-list="false" accept=".js">
                  <el-button type="primary">
                    <el-icon class="el-icon-upload2"></el-icon> 选择JS文件
                  </el-button>
                </el-upload>
                <div v-if="fileInfo" class="file-info">
                  <el-icon class="el-icon-document"></el-icon>
                  <span>{{ fileInfo.name }}</span>
                  <el-button size="small" type="text" @click="clearFile">清除</el-button>
                </div>
                <div v-else class="upload-hint">
                  请选择本地JavaScript文件
                </div>
              </div>
            </div>
          </el-tab-pane>
          <el-tab-pane label="网络脚本" name="url">
            <div class="url-script-container">
              <div class="section-header">
                <el-icon class="el-icon-link"></el-icon>
                <span>网络脚本URL</span>
              </div>
              <div class="url-input-area">
                <el-input v-model="scriptUrl" placeholder="输入网络脚本URL..." :disabled="running">
                  <template #append>
                    <el-button :disabled="!scriptUrl || running" @click="loadUrlScript">
                      <el-icon class="el-icon-download"></el-icon> 加载
                    </el-button>
                  </template>
                </el-input>
                <div v-if="urlInfo" class="url-info">
                  <el-icon class="el-icon-check"></el-icon>
                  <span>已加载: {{ urlInfo.url }}</span>
                  <el-button size="small" type="text" @click="clearUrl">清除</el-button>
                </div>
                <div v-else-if="scriptUrl" class="url-hint">
                  点击加载按钮获取脚本内容
                </div>
                <div v-else class="url-hint">
                  请输入网络脚本URL
                </div>
              </div>
            </div>
          </el-tab-pane>
        </el-tabs>
      </div>

      <!-- 输出结果区域 -->
      <div class="output-container">
        <div class="section-header">
          <el-icon class="el-icon-monitor"></el-icon>
          <span>执行结果</span>
        </div>
        <div class="output-content">
          <pre v-if="outputText" class="output-text">{{ outputText }}</pre>
          <div v-else class="no-output">暂无输出</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { injectScriptToActivateTab } from '@/utils/element-control';
import { TabPaneName } from 'element-plus';
import message from '@/message/index.js';

const ext = message.ext;

// 响应式数据
const activeTab = ref<TabPaneName>('code'); // 标签页：code, file, url
const scriptCode = ref('');
const outputText = ref('');
const running = ref(false);
const scriptUrl = ref('');
const fileInfo = ref<{ name: string; size: number } | null>(null);
const urlInfo = ref<{ url: string } | null>(null);

const emit = defineEmits(['add-message']);

// 执行脚本
async function executeScript() {
  let codeToExecute = '';

  switch (activeTab.value) {
    case 'code':
      if (!scriptCode.value.trim()) {
        emit('add-message', {
          message: '请输入JavaScript代码',
          type: 'warning'
        });
        return;
      }
      codeToExecute = scriptCode.value;
      break;
    case 'file':
      if (!fileInfo.value) {
        emit('add-message', {
          message: '请选择本地JavaScript文件',
          type: 'warning'
        });
        return;
      }
      codeToExecute = scriptCode.value;
      break;
    case 'url':
      if (!urlInfo.value) {
        emit('add-message', {   
          message: '请加载网络脚本',
          type: 'warning'
        });
        return;
      }
      codeToExecute = scriptCode.value;
      break;
  }

  running.value = true;
  outputText.value = '';

  try {
    // 直接执行脚本
    injectScriptToActivateTab({scriptStr: codeToExecute});

    // 显示执行成功信息
    outputText.value = '脚本已开始执行，请在控制台查看输出';
    emit('add-message', {
      type: 'success',
      message: '脚本执行开始'
    });
  } catch (error: any) {
    // 捕获执行错误
    outputText.value = `执行错误: ${error.message}\n${error.stack || ''}`;
    emit('add-message', {
      type: 'error',
      message: '脚本执行出错'
    });
  } finally {
    running.value = false;
  }
}

// 清空脚本
function clearScript() {
  scriptCode.value = '';
  outputText.value = '';
  fileInfo.value = null;
  urlInfo.value = null;
  scriptUrl.value = '';
  emit('add-message', {
    type: 'info',
    message: '已清空'
  });
}

// 复制结果
function copyResult() {
  if (outputText.value) {
    navigator.clipboard.writeText(outputText.value).then(() => {
      emit('add-message', {
        type: 'success',
        message: '结果已复制到剪贴板'
      });
    }).catch(() => {
      emit('add-message', {
        type: 'error',
        message: '复制失败'
      });
    });
  }
}

// 标签页切换
function handleTabChange(name: TabPaneName) {
  activeTab.value = name;
}

// 处理文件选择
function handleFileChange(file: any) {
  const selectedFile = file.raw;
  if (selectedFile) {
    const reader = new FileReader();
    reader.onload = (e: ProgressEvent<FileReader>) => {
      scriptCode.value = e.target?.result as string;
      fileInfo.value = {
        name: selectedFile.name,
        size: selectedFile.size
      };
      emit('add-message', {
        type: 'success',
        message: '文件读取成功'
      });
    };
    reader.onerror = () => {
      emit('add-message', {
        type: 'error',
        message: '文件读取失败'
      });
    };
    reader.readAsText(selectedFile);
  }
}

// 清除文件
function clearFile() {
  fileInfo.value = null;
  scriptCode.value = '';
}

// 加载网络脚本
async function loadUrlScript() {
  if (!scriptUrl.value.trim()) {
    emit('add-message', {
      type: 'warning',
      message: '请输入网络脚本URL'
    });
    return;
  }

  running.value = true;

  try {
    // 使用脚本执行服务加载网络脚本，绕过 CORS 限制
    const response = await ext.send({
      type: 'LOAD_URL_SCRIPT',
      payload: { url: scriptUrl.value },
      target: 'background'
    });

    if (!response.success) {
      throw new Error(response.error || '加载网络脚本失败');
    }

    const scriptContent = response.result;

    maLogger.log('加载的网络脚本内容:', scriptContent);
    scriptCode.value = scriptContent;
    urlInfo.value = {
      url: scriptUrl.value
    };
    emit('add-message', {
      type: 'success',
      message: '网络脚本加载成功'
    });
  } catch (error: any) {
    emit('add-message', {
      type: 'error',
      message: `网络脚本加载失败: ${error.message}`
    });
  } finally {
    running.value = false;
  }
}

// 清除URL
function clearUrl() {
  urlInfo.value = null;
  scriptUrl.value = '';
  scriptCode.value = '';
}
</script>

<style scoped>
.script-runner {
  padding: 20px;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

header {
  margin-bottom: 24px;
  text-align: center;
  color: #303133;
  padding: 20px;
  border-radius: 8px;
  background-color: #f5f7fa;
  border: 1px solid #e4e7ed;
}

header h1 {
  margin: 0;
  font-size: 1.5rem;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}

.content {
  max-width: 800px;
  margin: 0 auto;
}

.control-panel {
  margin-bottom: 20px;
}

.control-buttons {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}

.tab-container {
  margin-bottom: 20px;
}

.script-input-container,
.file-upload-container,
.url-script-container,
.output-container {
  margin-bottom: 20px;
}

.section-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 10px;
  font-weight: 500;
  color: #303133;
}

.code-editor,
.output-content {
  border: 1px solid #dcdfe6;
  border-radius: 6px;
  overflow: hidden;
}

textarea {
  width: 100%;
  padding: 12px;
  border: none;
  outline: none;
  font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
  font-size: 14px;
  resize: vertical;
  background-color: #fafafa;
}

textarea:readonly {
  background-color: #f5f7fa;
  cursor: not-allowed;
}

.upload-area {
  border: 1px solid #dcdfe6;
  border-radius: 6px;
  padding: 20px;
  background-color: #fafafa;
}

.file-info {
  margin-top: 10px;
  padding: 10px;
  background-color: #ecf5ff;
  border: 1px solid #d9ecff;
  border-radius: 4px;
  display: flex;
  align-items: center;
  gap: 10px;
}

.upload-hint {
  margin-top: 10px;
  color: #909399;
  font-size: 0.9rem;
}

.url-input-area {
  border: 1px solid #dcdfe6;
  border-radius: 6px;
  padding: 20px;
  background-color: #fafafa;
}

.url-info {
  margin-top: 10px;
  padding: 10px;
  background-color: #ecf5ff;
  border: 1px solid #d9ecff;
  border-radius: 4px;
  display: flex;
  align-items: center;
  gap: 10px;
}

.url-hint {
  margin-top: 10px;
  color: #909399;
  font-size: 0.9rem;
}

.output-content {
  min-height: 200px;
  background-color: #fafafa;
  position: relative;
}

.output-text {
  margin: 0;
  padding: 12px;
  font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
  font-size: 14px;
  line-height: 1.6;
  white-space: pre-wrap;
  word-break: break-all;
  color: #303133;
  max-height: 400px;
  overflow-y: auto;
}

.no-output {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: #909399;
  font-style: italic;
}

/* 滚动条样式 */
.output-text::-webkit-scrollbar,
textarea::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

.output-text::-webkit-scrollbar-track,
textarea::-webkit-scrollbar-track {
  background: #f1f1f1;
}

.output-text::-webkit-scrollbar-thumb,
textarea::-webkit-scrollbar-thumb {
  background: #c0c4cc;
  border-radius: 4px;
}

.output-text::-webkit-scrollbar-thumb:hover,
textarea::-webkit-scrollbar-thumb:hover {
  background: #909399;
}

/* 标签页样式 */
:deep(.el-tabs__header) {
  margin-bottom: 20px;
}

:deep(.el-tab-pane) {
  padding: 0;
}
</style>
