// src/pages/popup/views/CapturePage.vue
<template>
  <TableContainer>
    <template #head__left>
      <p class="section-kicker">Visual Inspector</p>
      <h2 class="section-title">组件捕获</h2>
      <p class="section-subtitle">从当前页面拾取任意组件，结构信息会同步显示到开发者工具。</p>
    </template>
    <template #head__right>
      <div class="capture-status" :class="captureStatusClass">
        <span>{{ captureStatusText }}</span>
      </div>
    </template>
    <template #default>
      <button class="capture-btn" :disabled="isCaptureDisabled" @click="triggerComponentCapture">
        <span class="capture-icon">⌖</span>
        <span class="capture-copy">
          <strong>开始捕获</strong>
          <small>点击后 popup 会自动关闭，随后在页面中点选目标组件。</small>
        </span>
      </button>

      <div class="capture-steps">
        <div class="step-card">
          <span class="step-index">01</span>
          <p>停留在需要分析的页面。</p>
        </div>
        <div class="step-card">
          <span class="step-index">02</span>
          <p>点击上方按钮进入捕获状态。</p>
        </div>
        <div class="step-card">
          <span class="step-index">03</span>
          <p>在页面中选择目标组件查看结果。</p>
        </div>
      </div>
    </template>
  </TableContainer>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { ExtMessage } from '@/types';
import { useDomainState } from '../composables/useDomainState';
import TableContainer from './TableContainer.vue';

const props = defineProps<{
  isActive: boolean;
}>();

const { isDomainDisabled, checkDomainStatus } = useDomainState();
const isCheckingSiteReadiness = ref(false);
const isContentScriptReady = ref<boolean | null>(null);

const captureStatusText = computed(() => {
  if (isDomainDisabled.value) {
    return '已禁止';
  }

  if (isCheckingSiteReadiness.value) {
    return '连接中';
  }

  if (isContentScriptReady.value) {
    return '已就绪';
  }

  return '未就绪';
});

const captureStatusClass = computed(() => {
  if (isDomainDisabled.value) {
    return 'capture-status--off';
  }

  if (isCheckingSiteReadiness.value) {
    return 'capture-status--pending';
  }

  return isContentScriptReady.value ? 'capture-status--on' : 'capture-status--off';
});

const isCaptureDisabled = computed(() => {
  return isDomainDisabled.value || isCheckingSiteReadiness.value || isContentScriptReady.value !== true;
});

const sendMessageToActiveContentScript = async (message: ExtMessage): Promise<any> => {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  maLogger.log('当前活动标签页:', tab);

  if (!tab?.id) {
    throw new Error('未找到当前活动标签页');
  }

  return new Promise((resolve, reject) => {
    chrome.tabs.sendMessage(tab.id!, { ...message, target: 'content' }, (response: any) => {
      if (chrome.runtime.lastError) {
        reject(new Error(chrome.runtime.lastError.message));
        return;
      }

      resolve(response);
    });
  });
};

const checkContentScriptReady = async (): Promise<void> => {
  try {
    const response = await sendMessageToActiveContentScript({
      type: 'POPUP_CAPTURE_HANDSHAKE',
    });
    isContentScriptReady.value = response?.success === true;
  } catch (error) {
    maLogger.log('当前站点内容脚本未就绪:', error);
    isContentScriptReady.value = false;
  }
};

const refreshCaptureStatus = async (): Promise<void> => {
  isCheckingSiteReadiness.value = true;
  isContentScriptReady.value = null;

  try {
    await Promise.allSettled([
      checkDomainStatus(),
      checkContentScriptReady(),
    ]);
  } finally {
    isCheckingSiteReadiness.value = false;
  }
};

const triggerComponentCapture = async (): Promise<void> => {
  if (isCaptureDisabled.value) {
    return;
  }

  try {
    maLogger.log('从popup触发组件捕获...');
    const res = await sendMessageToActiveContentScript({
      type: 'TRIGGER_COMPONENT_CAPTURE',
    });
    maLogger.log('组件捕获响应:', res);
    window.close();
  } catch (error) {
    maLogger.error('触发组件捕获失败:', error);
  }
};

watch(() => props.isActive, (isActive) => {
  if (!isActive) {
    return;
  }

  void refreshCaptureStatus();
});
</script>

<style scoped>
.section-kicker {
  margin: 0 0 8px;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--popup-accent);
}

.section-title {
  margin: 0;
  font-size: 22px;
  font-weight: 700;
  line-height: 1.1;
  color: var(--popup-text-primary);
}

.section-subtitle {
  margin: 8px 0 0;
  font-size: 13px;
  line-height: 1.5;
  color: var(--popup-text-muted);
}

.capture-status {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 64px;
  min-height: 34px;
  border-radius: 14px;
  font-size: 13px;
  font-weight: 700;
  color: var(--popup-text-primary);
  background: var(--popup-accent-gradient);
  border: 1px solid var(--popup-button-border);
}

.capture-status--on {
  color: var(--popup-success-text);
  background: var(--popup-success-bg);
  border-color: var(--popup-success-border);
}

.capture-status--pending {
  color: var(--popup-info-text);
  background: var(--popup-info-bg);
  border-color: var(--popup-info-border);
}

.capture-status--off {
  color: var(--popup-danger-text);
  background: var(--popup-danger-bg);
  border-color: var(--popup-danger-border);
}

.status-dot {
  flex-shrink: 0;
  width: 8px;
  height: 8px;
  border-radius: 50%;
}

.capture-status--on .status-dot {
  background: var(--popup-success-dot);
  box-shadow: 0 0 0 5px color-mix(in srgb, var(--popup-success-dot) 16%, transparent);
}

.capture-status--pending .status-dot {
  background: var(--popup-info-dot);
  box-shadow: 0 0 0 5px color-mix(in srgb, var(--popup-info-dot) 16%, transparent);
}

.capture-status--off .status-dot {
  background: var(--popup-danger-dot);
  box-shadow: 0 0 0 5px color-mix(in srgb, var(--popup-danger-dot) 16%, transparent);
}

.capture-btn {
  display: flex;
  align-items: center;
  gap: 14px;
  width: 100%;
  min-height: 84px;
  padding: 16px;
  border: 1px solid var(--popup-border-strong);
  border-radius: 20px;
  background: var(--popup-button-bg);
  color: var(--popup-text-on-accent);
  cursor: pointer;
  text-align: left;
  transition:
    transform 0.2s ease,
    box-shadow 0.2s ease,
    filter 0.2s ease;
  box-shadow: var(--popup-shadow-accent);
}

.capture-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: var(--popup-shadow-accent);
}

.capture-btn:disabled {
  cursor: not-allowed;
  filter: saturate(0.6);
  opacity: 0.6;
  box-shadow: none;
}

.capture-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 50px;
  height: 50px;
  border-radius: 16px;
  background: color-mix(in srgb, var(--popup-text-on-accent) 16%, transparent);
  font-size: 24px;
  font-weight: 700;
  box-shadow: var(--popup-inset-highlight);
}

.capture-copy {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.capture-copy strong {
  font-size: 17px;
  font-weight: 700;
}

.capture-copy small {
  font-size: 12px;
  line-height: 1.5;
  color: color-mix(in srgb, var(--popup-text-on-accent) 88%, transparent);
}

.capture-steps {
  display: grid;
  gap: 10px;
}

.step-card {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px;
  border-radius: 16px;
  border: 1px solid var(--popup-border);
  background: var(--popup-control-bg);
}

.step-index {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: 12px;
  background: var(--popup-accent-gradient);
  font-size: 12px;
  font-weight: 700;
  color: var(--popup-accent);
}

.step-card p {
  margin: 0;
  font-size: 13px;
  line-height: 1.5;
  color: var(--popup-text-muted);
}
</style>

// extension/src/pages/popup/views/CapturePage.tsx
/**
 * @author Zero
 * @version v2.0.0
 * @license MIT
 * @file src/pages/popup/views/CapturePage.tsx
 * @description React 版组件捕获页面 - 从当前页面拾取组件
 */
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { CameraOutlined } from '@ant-design/icons';
import TableContainer from '../components/TableContainer';
import { useDomainState } from '../composables/useDomainState';
import type { ExtMessage } from '@/types';
import './capture-page.scss';

/**
 * 组件捕获状态枚举
 */
type CaptureStatus = 'on' | 'pending' | 'off';

/**
 * 组件捕获页面组件
 */
export const CapturePage: React.FC = () => {
  const { isDomainDisabled, checkDomainStatus } = useDomainState();
  const [isCheckingSiteReadiness, setIsCheckingSiteReadiness] = useState(false);
  const [isContentScriptReady, setIsContentScriptReady] = useState<boolean | null>(null);

  /** 捕获状态文本 */
  const captureStatusText = useMemo(() => {
    if (isDomainDisabled) return '已禁止';
    if (isCheckingSiteReadiness) return '连接中';
    if (isContentScriptReady) return '已就绪';
    return '未就绪';
  }, [isDomainDisabled, isCheckingSiteReadiness, isContentScriptReady]);

  /** 捕获状态样式类 */
  const captureStatusClass = useMemo(() => {
    if (isDomainDisabled) return 'capture-status--off';
    if (isCheckingSiteReadiness) return 'capture-status--pending';
    return isContentScriptReady ? 'capture-status--on' : 'capture-status--off';
  }, [isDomainDisabled, isCheckingSiteReadiness, isContentScriptReady]);

  /** 是否禁用捕获按钮 */
  const isCaptureDisabled = useMemo(() => {
    return (
      isDomainDisabled ||
      isCheckingSiteReadiness ||
      isContentScriptReady !== true
    );
  }, [isDomainDisabled, isCheckingSiteReadiness, isContentScriptReady]);

  /** 向活动内容脚本发送消息 */
  const sendMessageToActiveContentScript = useCallback(async (
    message: ExtMessage,
  ): Promise<any> => {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    maLogger.log('当前活动标签页:', tab);

    if (!tab?.id) {
      throw new Error('未找到当前活动标签页');
    }

    return new Promise((resolve, reject) => {
      chrome.tabs.sendMessage(
        tab.id!,
        { ...message, target: 'content' },
        (response: any) => {
          if (chrome.runtime.lastError) {
            reject(new Error(chrome.runtime.lastError.message));
            return;
          }
          resolve(response);
        },
      );
    });
  }, []);

  /** 检查内容脚本是否就绪 */
  const checkContentScriptReady = useCallback(async (): Promise<void> => {
    try {
      const response = await sendMessageToActiveContentScript({
        type: 'POPUP_CAPTURE_HANDSHAKE',
      });
      setIsContentScriptReady(response?.success === true);
    } catch (error) {
      maLogger.log('当前站点内容脚本未就绪:', error);
      setIsContentScriptReady(false);
    }
  }, [sendMessageToActiveContentScript]);

  /** 刷新捕获状态 */
  const refreshCaptureStatus = useCallback(async (): Promise<void> => {
    setIsCheckingSiteReadiness(true);
    setIsContentScriptReady(null);

    try {
      await Promise.allSettled([checkDomainStatus(), checkContentScriptReady()]);
    } finally {
      setIsCheckingSiteReadiness(false);
    }
  }, [checkDomainStatus, checkContentScriptReady]);

  /** 触发组件捕获 */
  const triggerComponentCapture = useCallback(async (): Promise<void> => {
    if (isCaptureDisabled) return;

    try {
      maLogger.log('从popup触发组件捕获...');
      const res = await sendMessageToActiveContentScript({
        type: 'TRIGGER_COMPONENT_CAPTURE',
      });
      maLogger.log('组件捕获响应:', res);
      window.close();
    } catch (error) {
      maLogger.error('触发组件捕获失败:', error);
    }
  }, [isCaptureDisabled, sendMessageToActiveContentScript]);

  /** 初始化加载捕获状态 */
  useEffect(() => {
    refreshCaptureStatus();
  }, [refreshCaptureStatus]);

  return (
    <TableContainer
      headLeft={
        <>
          <p className="section-kicker">Visual Inspector</p>
          <h2 className="section-title">组件捕获</h2>
          <p className="section-subtitle">
            从当前页面拾取任意组件，结构信息会同步显示到开发者工具。
          </p>
        </>
      }
      headRight={
        <div className={`capture-status ${captureStatusClass}`}>
          <span className="status-dot"></span>
          <span>{captureStatusText}</span>
        </div>
      }
    >
      <button
        className="capture-btn"
        disabled={isCaptureDisabled}
        onClick={triggerComponentCapture}
      >
        <span className="capture-icon">
          <CameraOutlined />
        </span>
        <span className="capture-copy">
          <strong>开始捕获</strong>
          <small>点击后 popup 会自动关闭，随后在页面中点选目标组件。</small>
        </span>
      </button>

      <div className="capture-steps">
        <div className="step-card">
          <span className="step-index">01</span>
          <p>停留在需要分析的页面。</p>
        </div>
        <div className="step-card">
          <span className="step-index">02</span>
          <p>点击上方按钮进入捕获状态。</p>
        </div>
        <div className="step-card">
          <span className="step-index">03</span>
          <p>在页面中选择目标组件查看结果。</p>
        </div>
      </div>
    </TableContainer>
  );
};

export default CapturePage;
